/**
 * GERADO AUTOMATICAMENTE por scripts/generate-manifest.ts
 * Não edite à mão — rode: pnpm tsx scripts/generate-manifest.ts
 *
 * Cada path mapeia (locale → import dinâmico do MDX).
 * Usar via carregarMdxLocalizado(caminho, locale) em manifest.ts.
 */
import type { ComponentType } from 'react'

type MdxLoader = () => Promise<{ default: ComponentType }>

export const manifestoI18n: Record<string, Partial<Record<string, MdxLoader>>> = {
  'aulas/ano-1/trim-1/licao-01-conjuntos-intervalos': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-01-conjuntos-intervalos.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-01-conjuntos-intervalos.mdx'),
  },
  'aulas/ano-1/trim-1/licao-02-funcoes': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'ja-JP': () => import('@/../content/i18n/ja-JP/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'ko-KR': () => import('@/../content/i18n/ko-KR/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'ru-RU': () => import('@/../content/i18n/ru-RU/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-1/licao-02-funcoes.mdx'),
  },
  'aulas/ano-1/trim-1/licao-04-quadratica': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'ja-JP': () => import('@/../content/i18n/ja-JP/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'ko-KR': () => import('@/../content/i18n/ko-KR/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'pl-PL': () => import('@/../content/i18n/pl-PL/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'ru-RU': () => import('@/../content/i18n/ru-RU/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-1/licao-04-quadratica.mdx'),
  },
  'aulas/ano-1/trim-1/licao-05-composicao-inversa': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'ja-JP': () => import('@/../content/i18n/ja-JP/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'ko-KR': () => import('@/../content/i18n/ko-KR/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'pl-PL': () => import('@/../content/i18n/pl-PL/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'ru-RU': () => import('@/../content/i18n/ru-RU/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-1/licao-05-composicao-inversa.mdx'),
  },
  'aulas/ano-1/trim-1/licao-06-exponencial': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'ja-JP': () => import('@/../content/i18n/ja-JP/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'ko-KR': () => import('@/../content/i18n/ko-KR/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'pl-PL': () => import('@/../content/i18n/pl-PL/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'ru-RU': () => import('@/../content/i18n/ru-RU/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-1/licao-06-exponencial.mdx'),
  },
  'aulas/ano-1/trim-1/licao-07-logaritmo': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'ja-JP': () => import('@/../content/i18n/ja-JP/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'ko-KR': () => import('@/../content/i18n/ko-KR/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'pl-PL': () => import('@/../content/i18n/pl-PL/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'ru-RU': () => import('@/../content/i18n/ru-RU/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-1/licao-07-logaritmo.mdx'),
  },
  'aulas/ano-1/trim-1/licao-08-crescimento': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
    'ja-JP': () => import('@/../content/i18n/ja-JP/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
    'ru-RU': () => import('@/../content/i18n/ru-RU/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-1/licao-08-crescimento.mdx'),
  },
  'aulas/ano-1/trim-1/licao-09-taxa-variacao': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
    'ja-JP': () => import('@/../content/i18n/ja-JP/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
    'ru-RU': () => import('@/../content/i18n/ru-RU/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-1/licao-09-taxa-variacao.mdx'),
  },
  'aulas/ano-1/trim-1/licao-10-consolidacao-trim-1': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
    'ja-JP': () => import('@/../content/i18n/ja-JP/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
    'ru-RU': () => import('@/../content/i18n/ru-RU/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-1/licao-10-consolidacao-trim-1.mdx'),
  },
  'aulas/ano-1/trim-2/licao-11-trig-triangulo': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-2/licao-11-trig-triangulo.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-2/licao-11-trig-triangulo.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-2/licao-11-trig-triangulo.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-2/licao-11-trig-triangulo.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-2/licao-11-trig-triangulo.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-2/licao-11-trig-triangulo.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-2/licao-11-trig-triangulo.mdx'),
  },
  'aulas/ano-1/trim-2/licao-12-circulo-trigonometrico': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-2/licao-12-circulo-trigonometrico.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-2/licao-12-circulo-trigonometrico.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-2/licao-12-circulo-trigonometrico.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-2/licao-12-circulo-trigonometrico.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-2/licao-12-circulo-trigonometrico.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-2/licao-12-circulo-trigonometrico.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-2/licao-12-circulo-trigonometrico.mdx'),
  },
  'aulas/ano-1/trim-2/licao-13-funcoes-trigonometricas': {
    'pt-BR': () => import('@/../content/aulas/ano-1/trim-2/licao-13-funcoes-trigonometricas.mdx'),
    'de-DE': () => import('@/../content/i18n/de-DE/aulas/ano-1/trim-2/licao-13-funcoes-trigonometricas.mdx'),
    'en-US': () => import('@/../content/i18n/en-US/aulas/ano-1/trim-2/licao-13-funcoes-trigonometricas.mdx'),
    'es-ES': () => import('@/../content/i18n/es-ES/aulas/ano-1/trim-2/licao-13-funcoes-trigonometricas.mdx'),
    'fr-FR': () => import('@/../content/i18n/fr-FR/aulas/ano-1/trim-2/licao-13-funcoes-trigonometricas.mdx'),
    'it-IT': () => import('@/../content/i18n/it-IT/aulas/ano-1/trim-2/licao-13-funcoes-trigonometricas.mdx'),
    'zh-CN': () => import('@/../content/i18n/zh-CN/aulas/ano-1/trim-2/licao-13-funcoes-trigonometricas.mdx'),
  },
  'calculo-1/derivadas/o-que-e-derivada': {
    'pt-BR': () => import('@/../content/calculo-1/derivadas/o-que-e-derivada.mdx'),
  },
  'financas-quantitativas/opcoes/black-scholes': {
    'pt-BR': () => import('@/../content/financas-quantitativas/opcoes/black-scholes.mdx'),
  },
  'metodos-numericos/zero-de-funcoes/bissecao': {
    'pt-BR': () => import('@/../content/metodos-numericos/zero-de-funcoes/bissecao.mdx'),
  },
  'metodos-numericos/zero-de-funcoes/newton-raphson': {
    'pt-BR': () => import('@/../content/metodos-numericos/zero-de-funcoes/newton-raphson.mdx'),
  },
}
