# -*- coding: utf-8 -*-
"""SistemasLineares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYKQZwDREI74UO_llqkRYdc0uDQx-PXG
"""

import copy

A = [[5,1,1,1],[5,6,-1,1],[1,-1,5,-1],[1,1,2,8]]
b = [10,20,10,5]
chuteC = [1,1,1,1]

def criterioA(A,b,chute):
  soma_final = 0
  for linha in range(len(A)):
    soma_linha = b[linha]
    for coluna in range(len(A[linha])):
      soma_linha -= A[linha][coluna]*chute[coluna]
    soma_final += abs(soma_linha)
  return soma_final

def jacobi(A,b,chute,criterio):
  chute_new = copy.deepcopy(chute)
  linhas = len(chute)
  for iteracao in range(100):
    print(iteracao+1)
    for linha in range(linhas):
      soma = b[linha]/A[linha][linha]
      for coluna in range(len(A[linha])):
        if coluna != linha:
          soma -= A[linha][coluna]*chute[coluna]/A[linha][linha]
      chute_new[linha] = soma
    chute = copy.deepcopy(chute_new)
    print(chute)
    if criterioA(A,b,chute) < criterio:

      break



  return chute

def gauss_s(A,b,chute,criterio):
  linhas = len(chute)
  for iteracao in range(10):
    for linha in range(linhas):
      soma = b[linha]/A[linha][linha]
      for coluna in range(len(A[linha])):
        if coluna != linha:
          soma -= A[linha][coluna]*chute[coluna]/A[linha][linha]
      chute[linha] = soma


  return chute

jacobi(A,b,chuteC,0.001)

gauss_s(A,b,chute,0.01)

criterioA(A,b,chute)