# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkvuVVaXkV10CEgReIoBTNhE3xJWMdzl
"""

import sympy as sp
import numpy as np
from sympy.parsing.sympy_parser import parse_expr

x = sp.Symbol('x')

def F(funcao, y):
  return funcao.evalf(subs= {x:y})

def bissec(a,b,criterio,funcao):
  if F(funcao, a)*F(funcao, b)>0:
    print('Não é possível afirmar que há raizes entre a e b!')
  else:
    media = (a+b)/2
    i = 0
    while abs(F(funcao, media))>criterio:
      media = (a+b)/2
      print(f'A média da iteração {i} é: {media}')
      print("O valor dessa função na raiz é: " + str(F(funcao, media)))
      if F(funcao, a)*F(funcao, media)>0:
        a = media
      else:
        b = media
      i+=1
  print("A raiz da função é: " + str(media))

def newton(inicial, criterio, funcao):
  if F(funcao, inicial) == 0:
    print(f"A raiz é o valor {inicial}")
  while abs(F(funcao, inicial))>criterio:
    derivada = sp.diff(funcao)
    valor_derivada = derivada.evalf(subs= {x:inicial})
    if valor_derivada == 0:
      print("Não é possível utilizar o método de Newton!")
      break
    inicial = inicial - F(funcao, inicial)/valor_derivada
  print("A raiz da função é: " + str(inicial))

def secante(a,b,criterio,funcao):
  f_a = F(funcao, a)
  f_b = F(funcao, b)
  while abs(f_b) > criterio:
    f_a = F(funcao, a)
    f_b = F(funcao, b)
    proximo = (a*f_b-b*f_a)/(f_b-f_a)
    a = b
    b = proximo


  print("A raiz da função é: " + str(b))

def ZeroFuncao(metodo):
  if metodo == 'bissec':
    funcao = input("Digite a função:")
    a = float(input("Digite o valor de a:"))
    b = float(input("Digite o valor de b:"))
    criterio = float(input("Digite o valor do criterio:"))
    bissec(a,b,criterio, parse_expr(funcao))
  elif metodo == 'newton':
    funcao = input("Digite a função:")
    inicial = float(input("Digite o valor inicial:"))
    criterio = float(input("Digite o valor do criterio:"))
    newton(inicial, criterio, parse_expr(funcao))
  elif metodo == 'secante':
    funcao = input("Digite a função:")
    a = float(input("Digite o valor de xk-1:"))
    b = float(input("Digite o valor de xk:"))
    criterio = float(input("Digite o valor do criterio:"))
    secante(a,b,criterio, parse_expr(funcao))
  else:
    print("Método não encontrado!")

ZeroFuncao('bissec')