/**
 * Frases curtas de incentivo ao estudo de matemática — PT-BR.
 *
 * Tom: avô carinhoso torcendo por 12 netos. Direto, caloroso, sem
 * paternalismo. Não inventa citações: quando há autor + ano, é frase
 * documentada (livro, artigo, palestra). O resto é frase do projeto,
 * sem atribuição.
 *
 * Uso: <CheerBanner /> escolhe uma aleatoriamente por mount.
 */

export type Cheer = string | { t: string; a: string; y?: string }

export const CHEERS: Cheer[] = [
  // ===== Sementes do dono (5) =====
  'Matemática é para sempre.',
  'Aprendizado continuado é importante hoje e será mais ainda no futuro.',
  'Invista seu tempo em você, no seu conhecimento.',
  'Matemática serve da vida pessoal aos concursos: ANPAD, ANPEC, BACEN, ENEM.',
  'Todo programa de pós-graduação quantitativo usa cálculo e estatística.',

  // ===== Persistência e disciplina (carinho de avô) =====
  'Faz hoje o pouco que dá. Amanhã, o pouco de hoje vira muito.',
  'Quem volta toda noite ao caderno aprende, sem pressa, mas aprende.',
  'Errar uma vez é caminho. Errar dez vezes é treino. Errar e desistir é perda.',
  'O método não é dom: é hábito. Você pega aos poucos.',
  'Dois exercícios por dia, durante um ano, são mais de setecentos.',
  'Aprender matemática é como cuidar de uma horta: regue todo dia.',
  'Não se aprende fórmula. Aprende-se a usá-la em problema novo.',
  'O caderno fala. Cada erro escrito é uma aula sua, dada por você.',
  'Decorar fórmula sem entender é pão dormido: enche, mas não nutre.',
  'Quando a conta não fechar, volte ao começo. Sempre fecha lá.',
  'Você tem o direito de ser lento. Não tem o direito de parar.',
  'Cada problema vencido fica seu. Ninguém te tira.',
  'Faça o exercício difícil mesmo se demorar uma hora: a hora vira sua.',
  'A página em branco é o teste de coragem.',
  'Quem só copia a solução não aprende. Quem refaz sozinho, aprende.',
  'Repetir é treinar. Treinar é saber.',
  'Não se compare com colega: compare com você de uma semana atrás.',
  'O aluno mediano que estuda todo dia passa o talentoso que estuda véspera.',
  'A disciplina é o talento que você fabrica.',
  'Estudo é juro composto: quem começa cedo, colhe muito mais.',
  'A constância vence a intensidade. Sempre.',
  'Se hoje rendeu pouco, registre. Amanhã rende mais.',
  'Pequenos passos diários fazem grandes percursos.',
  'Quem para na primeira dificuldade chega no mesmo lugar de quem nem começou.',
  'A persistência é o melhor multiplicador.',
  'Não desanime com a página rabiscada — é nela que o aprendizado mora.',
  'Cinco páginas por dia, em um ano, viram um livro inteiro.',
  'A matemática espera por você. Volte sempre.',
  'O cansaço passa. O entendimento fica.',
  'Cada tentativa errada elimina um caminho. Aproxima do certo.',
  'Lápis na mão, mente quieta, e o problema cede.',
  'Não pule etapa por preguiça: pula por já ter dominado.',
  'A criança aprende a andar caindo. Você aprende cálculo errando.',
  'Quem treina pouco, esquece. Quem treina sempre, automatiza.',
  'A disciplina silenciosa supera o entusiasmo barulhento.',
  'Sente-se. Abra o livro. Resolva um. Fechou o dia.',
  'O bom estudante volta no mesmo problema três vezes em semanas diferentes.',
  'Não terminou hoje? Marque a página. Continue amanhã.',
  'Aprender custa tempo. Não saber custa muito mais.',
  'A pressa atrapalha demonstração. Demonstração quer paciência.',
  'Você não tem que ser rápido. Tem que ser correto.',
  'Não adianta ler vinte páginas e fazer zero exercício.',
  'Faça primeiro. Verifique depois.',
  'Quem entende a regra, dispensa truque.',
  'Hoje é página fácil; amanhã, página difícil. Ambas contam.',
  'Não confunda cansaço com bloqueio: durma, volte, resolva.',
  'Quando travou, levante, beba água, volte. O cérebro agradece.',
  'O caminho longo é o caminho seguro.',
  'Quem não erra não aprende; quem só erra também não.',
  'Termine o exercício antes de olhar a resposta.',
  'Confiança vem de já ter resolvido. Resolva, então.',

  // ===== Fundamentos / ler livro / método =====
  'Sem fração e sem porcentagem, não tem economia, não tem ciência, não tem nada.',
  'A álgebra do oitavo ano abre a porta do cálculo.',
  'Funções afim e quadrática são esqueleto. Tudo o resto é músculo em cima.',
  'Domínio é onde a função está viva. Sem domínio, não há função.',
  'O conjunto dos reais não é decorado: é construído.',
  'Trigonometria é a linguagem do círculo. Quem fala, lê o mundo.',
  'A reta numérica é o primeiro mapa do mundo.',
  'Porcentagem é fração disfarçada de número grande.',
  'Quem domina logaritmo entende crescimento.',
  'Geometria analítica casou álgebra com geometria — e o mundo nunca foi o mesmo.',
  'Vetor é direção com tamanho. Aprenda os dois.',
  'Combinação não tem ordem. Arranjo tem. Não confunda.',
  'O zero é um número. Convenção brasileira inclui ele nos naturais.',
  'A fração 1/2 é mais útil que a calculadora.',
  'Limite é a versão honesta do "perto".',
  'A derivada mede taxa. Tudo que muda tem derivada.',
  'A integral acumula. Tudo que se soma de pedacinho infinitesimal, integra.',
  'Aprenda a olhar gráfico antes de fazer conta.',
  'Saber ler enunciado é metade da prova.',
  'Quem entende notação decifra o livro inteiro.',
  'Erro de sinal mata. Confira sempre o sinal.',
  'A unidade fala: metro, segundo, real. Verifique a unidade.',
  'Estimativa antes da conta: você pega erro grosseiro de imediato.',
  'Faça o desenho. Sempre. Mesmo no problema "abstrato".',
  'O melhor aluno desenha. O segundo melhor escreve. O terceiro decora.',
  'Quando não souber por onde começar, escreva os dados.',
  'Termo desconhecido recebe nome e vira variável.',
  'A boa notação resolve metade do problema.',
  'Use parênteses sempre que houver dúvida. Sempre.',
  'A álgebra é manipulação simbólica honesta. Não trapaceie.',
  'Cancele com cuidado. Cancela só fator multiplicativo.',
  'Não some embaixo da raiz como se fossem termos linhares.',
  'Não distribua exponencial em soma. Nunca.',
  'Decimal é fração disfarçada. Trabalhe com fração quando puder.',
  'Estime primeiro. Calcule depois. Compare. Aprenda.',
  'A boa demonstração não usa atalhos não justificados.',
  'Toda implicação tem hipótese. Lembre da hipótese.',
  'Contraexemplo derruba conjectura. Procure contraexemplo antes de tentar provar.',
  'Defina, depois opere. Sem definição, opera no escuro.',
  'A definição não é negociável. Use exatamente a que está no livro.',
  'O bom estudante refaz a definição com palavras próprias.',
  'Antes de provar, convença-se com exemplo pequeno.',
  'O exemplo concreto é mãe da intuição.',
  'O caso particular é a porta do caso geral.',
  'Toda teoria começou com um caso pequeno bem entendido.',
  'Aprenda a aproximar antes de aprender a calcular exato.',
  'A ordem de grandeza é mais importante que a vírgula.',
  'Saber que algo cresce exponencial é mais útil que saber a base.',
  'Cobertura, não cobertura: lema fundamental da topologia básica.',
  'Convergir é se aproximar para sempre. Não basta chegar perto uma vez.',
  'A indução é amiga: base, hipótese, passo, fim.',
  'A demonstração por contradição é cabra-cega: assume o oposto e tropeça.',
  'Por absurdo, supõe-se o contrário; chega-se ao impossível; volta-se com a verdade.',
  'Lema é teorema pequeno que abre porta de teorema grande.',
  'Corolário é teorema que cai no colo depois do teorema principal.',
  'A axiomática é o solo. Sem ela, não há prédio.',
  'A função composta é função de função. Calma. Faz uma camada por vez.',
  'A função inversa desfaz. Verifique sempre: f(f⁻¹(x)) = x.',
  'O gráfico da inversa é o reflexo no eixo y = x.',
  'Toda função estritamente monótona tem inversa.',
  'Não inverta em pedaços onde a função não é injetora.',
  'A continuidade preserva limites. Sem continuidade, o limite engana.',
  'A diferenciabilidade implica continuidade — mas não o contrário.',
  'O teorema do valor médio cobra: pra cá ou pra lá, mas em algum lugar a derivada bate.',
  'Bolzano garante: contínua que muda de sinal tem raiz no intervalo.',
  'O teorema fundamental do cálculo amarra derivada e integral. Pilar do edifício.',
  'A regra da cadeia é a regra da composição. Decoração: derivada do de fora vezes derivada do de dentro.',
  'Integração por partes é u dv = uv − ∫ v du. Decore o ritmo.',
  'Substituição é troca de variável. Mude com cuidado o limite de integração.',
  'Frações parciais quebram quociente em pedaços fáceis.',
  'Série geométrica converge se a razão tem módulo menor que um.',
  'p-série converge se p maior que um. Decore os dois casos.',
  'Convergência absoluta implica convergência simples. O contrário não.',
  'Teste da razão fala em limite. Teste da raiz também. Use o que for mais limpo.',
  'A série de Taylor aproxima função analítica numa vizinhança.',
  'O resto de Taylor mede o erro. Saber estimar resto é saber usar Taylor.',

  // ===== Carreira / mercado =====
  'Quem sabe matemática negocia melhor.',
  'Mercado paga quem entende risco. Risco é matemática.',
  'O analista quantitativo é matemático com cara de engravatado.',
  'Programar bem não substitui pensar bem em matemática.',
  'A IA roda em álgebra linear. Quem não sabe matriz fica de fora.',
  'Dados sem estatística são números sem sentido.',
  'O cientista de dados sério passa antes pela estatística.',
  'Engenharia financeira é cálculo aplicado a dinheiro.',
  'Atuário é matemático que aprendeu seguros.',
  'Quem entende juros compostos não cai em parcelado caro.',
  'Saber porcentagem evita o cartão de crédito devorando você.',
  'O CDI é matemática diária. Aprenda a contar dias úteis.',
  'A taxa Selic é índice. Saber lê-la é saber economia.',
  'O econometrista trabalha com regressão. Regressão é cálculo + álgebra linear.',
  'Sem cálculo não tem otimização. Sem otimização, ninguém escala negócio.',
  'Um bom modelo vale mais que cem palpites.',
  'Quem desenha modelo conta uma história em equações.',
  'O programador sênior resolve com matemática o que o júnior resolve com força bruta.',
  'A dívida cresce em juros compostos. Sua poupança também.',
  'O segredo do enriquecimento é o tempo. Tempo aplicado em juros compostos.',
  'A planilha sem matemática é planilha bonita e errada.',
  'Toda decisão financeira tem uma equação por trás.',
  'O economista aplicado vive de cálculo, álgebra linear e estatística.',
  'Você não precisa ser gênio. Precisa ser disciplinado.',
  'Engenharia é matemática transformada em coisa.',
  'Quem entende otimização entende a indústria.',
  'O profissional bom faz contas. O melhor faz contas certas.',
  'Programação dinâmica é matemática que vira algoritmo.',
  'O machine learning bom é cálculo + álgebra linear + estatística.',
  'Não tem ciência da computação séria sem matemática discreta.',
  'A criptografia que protege seu PIX é teoria dos números.',
  'O FBI usa estatística para perfilar fraude. Você também pode.',
  'Cabeça que conta evita ser enganada.',
  'O dia a dia da empresa é regressão. Aprenda regressão.',
  'O CFO bom entende fluxo descontado. É cálculo aplicado.',
  'Empreendedor matemático escala dez vezes mais.',
  'Quem mede, melhora. Medir é matemática.',
  'O bom gestor decide com média e desvio. Aprenda os dois.',
  'A estatística é o filtro entre o ruído e o sinal.',
  'O viés é o inimigo silencioso. Aprenda a vê-lo.',
  'Quem entende viés de seleção lê notícia melhor.',
  'A correlação não é causa. Memorize.',
  'A causalidade exige desenho cuidadoso. Aprenda desenho.',
  'Variável instrumental é truque inteligente. Vale aprender.',
  'O método de diferenças em diferenças é simples e poderoso.',
  'Regressão descontínua é arte. Vale o esforço.',
  'A inferência causal é a fronteira do mercado quantitativo.',
  'Engenheiro que sabe matemática vira líder técnico.',
  'O pesquisador científico vive de equação diferencial.',
  'A medicina baseada em evidências é estatística.',
  'O epidemiologista usa modelo SIR. É equação diferencial.',
  'O climatologista resolve EDPs em supercomputador.',
  'A previsão do tempo é matemática numérica em escala.',
  'Sem matemática, não tem GPS, não tem PIX, não tem internet.',
  'O bitcoin é matemática: criptografia + teoria dos jogos.',
  'A blockchain é hash + assinatura digital. Matemática pura.',
  'A IA generativa é gradiente descendente em escala absurda.',
  'Quem entende derivada parcial entende treino de rede neural.',
  'O backpropagation é regra da cadeia automatizada.',
  'A função de custo cai por gradiente. Cálculo, sempre.',
  'Saber matemática te coloca dois passos à frente.',
  'O concurso público quantitativo paga bem. Estude.',
  'O analista do BACEN ganha mais que muito gerente. Estatística avançada.',
  'O analista do BNDES sabe finanças quantitativas.',
  'O IPEA contrata economista PhD. Pós-graduação séria.',
  'O CADE precisa de econometrista. Causalidade no varejo.',
  'O TCU contrata auditor com base quantitativa.',
  'Receita Federal valoriza quem entende estatística aplicada.',
  'A Polícia Federal contrata perito matemático para fraude.',
  'O atuário do CESGRANRIO trabalha com tábuas de mortalidade. Estatística pura.',
  'Banco do Brasil tem cargos quantitativos que pagam bem.',
  'Caixa contrata para área de risco. Estatística e cálculo.',
  'Petrobras contrata engenheiro quantitativo. Otimização em campos de petróleo.',
  'Vale e CSN contratam para área de planejamento. Pesquisa operacional.',
  'O setor de energia paga quem entende otimização estocástica.',
  'A Polícia Civil tem perícia digital e financeira. Matemática.',
  'O auditor independente que entende estatística é raro e caro.',
  'O auditor da CGU que sabe amostragem estatística vira coordenador rápido.',
  'O analista de risco bancário ganha bem desde o início.',
  'Quem fala estatística e finanças passa em concurso de ANBIMA.',
  'A CVM contrata para área de fiscalização. Estatística aplicada a mercado.',
  'A ANS valoriza quem entende atuária.',
  'A SUSEP é o reino do atuário no Brasil.',
  'A área de modelagem do banco é refúgio de matemático.',
  'Quem domina cálculo + Python entra em qualquer fintech.',
  'A pesquisa de IFE da PF e RFB pede estatística avançada.',

  // ===== Provas e concursos brasileiros =====
  'O ENEM premia quem sabe interpretar texto matemático. Treine ler enunciado.',
  'A OBMEP é portão de entrada para olimpíada internacional. Comece cedo.',
  'O ITA pede mais que cálculo: pede pensar matematicamente.',
  'O IME aceita quem domina geometria com rigor.',
  'A AFA, EFOMM, EsPCEx valorizam matemática sólida.',
  'A primeira fase da OBMEP avalia raciocínio simples e profundo.',
  'A segunda fase da OBMEP é onde mora a beleza.',
  'A OBM é olimpíada nacional de matemática. Vale para currículo de bolsa.',
  'A IMO é a olimpíada mundial. Você não precisa chegar lá — só estudar como se fosse.',
  'A Olimpíada de Maio é boa para 8º e 9º anos. Aprenda lá.',
  'A Olimpíada Cone Sul reúne países vizinhos. Conhecer faz bem.',
  'O Vestibular FUVEST cobra cálculo conceitual. Estude com calma.',
  'A UNICAMP cobra rigor algébrico. Treine identidades.',
  'A UFRGS cobra leitura de gráfico. Faça muitos.',
  'A UFRJ exige geometria analítica firme.',
  'O concurso BACEN ANALISTA cobra estatística avançada.',
  'O ANPEC é o portão para mestrado em economia. Cálculo + álgebra linear + estatística.',
  'O ANPAD é prova de admissão a mestrado em administração. Quantitativo conta muito.',
  'O CFA tem três níveis. Os três pedem estatística e finanças.',
  'A CFA Level I cobra estatística descritiva e probabilidade.',
  'A CFA Level II é álgebra linear aplicada a portfólio.',
  'A FRM (Financial Risk Manager) é matemática financeira séria.',
  'O Charterholder do CFA carrega prêmio de salário substancial.',
  'A prova do CESGRANRIO para Petrobras tem matemática de nível superior.',
  'A FGV cobra prova quantitativa para diversos cargos federais.',
  'O CESPE/CEBRASPE valoriza interpretação de tabela e gráfico.',
  'A FCC pede aritmética rápida. Treine cálculo mental.',
  'A VUNESP é objetiva: domínio de fração e porcentagem é decisivo.',
  'A IBFC pede raciocínio lógico matemático. Treine silogismos.',
  'O TJ-SP tem cargo de analista com peso quantitativo.',
  'O concurso do TRT favorece quem entende estatística para auditoria.',
  'O DPF (Polícia Federal) tem prova com lógica e raciocínio.',
  'A PRF cobra raciocínio matemático com tempo curto. Treine velocidade.',
  'O CACD do Itamaraty tem prova de raciocínio quantitativo. Não negligencie.',
  'O concurso da Câmara dos Deputados paga muito bem. Estude.',
  'A SEFAZ-SP de Fiscal pede matemática financeira pesada.',
  'A SEFAZ-RJ de Auditor cobra estatística aplicada.',
  'A SEFAZ-PE valoriza álgebra linear básica.',
  'A SEFAZ-MG cobra cálculo de juros simples e compostos.',
  'O tribunal de contas estadual tem prova quantitativa relevante.',
  'A Procuradoria Geral do Estado tem cargos que cobram lógica.',
  'A Defensoria Pública valoriza interpretação numérica.',

  // ===== Pós-graduação / academia =====
  'O mestrado stricto sensu pede maturidade matemática. Comece pelo cálculo.',
  'O doutorado em economia exige domínio de cálculo III + álgebra linear.',
  'A pós em estatística começa por probabilidade rigorosa.',
  'A pós em engenharia pede equações diferenciais.',
  'A pós em administração valoriza pesquisa quantitativa.',
  'O doutorado em finanças quantitativas é leitura constante de papers.',
  'O artigo bom tem matemática rigorosa e dado bem analisado.',
  'A revisão por pares é a peneira da ciência.',
  'O Working Paper é onde a fronteira aparece primeiro.',
  'A bibliografia é mapa: leia os clássicos antes dos novos.',
  'O método científico tem matemática como linguagem.',
  'O bolsista de iniciação científica que estuda matemática tem futuro.',
  'A monografia bem feita usa estatística com cuidado.',
  'A dissertação de mestrado mostra que você sabe ler e replicar.',
  'A tese de doutorado prova que você sabe criar.',
  'O orientador valoriza aluno disciplinado mais que aluno brilhante.',
  'O grupo de estudo aprende junto. Encontre um.',
  'O livro do Stewart é cálculo padrão no Brasil.',
  'O Boldrini é álgebra linear leitura clássica.',
  'O Lima da SBM é nosso clássico nacional. Vale ler.',
  'O Hoffman & Kunze é álgebra linear de outro nível. Para o sério.',
  'O Halmos é elegância. Leia quando estiver pronto.',
  'O Strang é álgebra linear amigável. Pra começar.',
  'O Casella & Berger é estatística para mestrado.',
  'O DeGroot é probabilidade clara.',
  'O Wasserman é "All of Statistics". Leitura veloz e profunda.',
  'O Hastie, Tibshirani & Friedman é "Elements of Statistical Learning". Padrão da área.',
  'O Bishop "Pattern Recognition" é referência em ML.',
  'O Goodfellow "Deep Learning" é livro-base de redes neurais.',

  // ===== Vida prática / decisões =====
  'O preço à vista mostra o juro embutido na parcela.',
  'O parcelado sem juros tem juros. Está embutido. Pesquise o à vista.',
  'A inflação corrói. Saber matemática protege.',
  'A taxa real de juros é (nominal − inflação)/(1+inflação). Decore.',
  'O Tesouro Direto é matemática financeira pura. Aprenda.',
  'A CDB com liquidez diária só rende se você não sacar.',
  'O LCA e LCI têm imposto zero, mas prazo. Calcule.',
  'O fundo imobiliário paga rendimento mensal. Entenda o yield.',
  'A previdência privada tem taxa de carregamento. Cuidado.',
  'A diversificação reduz risco. É matemática: covariância.',
  'O retorno esperado e a volatilidade são duas faces da moeda.',
  'A mediana é mais robusta que a média.',
  'O desvio padrão fala mais que o range.',
  'O percentil é seu amigo quando há outlier.',
  'O IMC é fórmula. Aprenda a interpretar com contexto.',
  'A taxa de batimentos máxima é 220 menos sua idade. Use no exercício.',
  'A receita de bolo é proporção. Quem sabe regra de três cozinha bem.',
  'A escala do mapa é razão. Entenda razão para entender mapa.',
  'O saldo do cartão de crédito cresce em juros compostos altos. Não atrase.',
  'O fluxo de caixa pessoal é uma planilha simples. Faça.',
  'O orçamento por categoria reduz ansiedade. Faça com lápis se preciso.',
  'A reserva de emergência é seis vezes seu gasto mensal.',
  'A regra 50-30-20 é um começo: 50% essenciais, 30% lazer, 20% poupança.',
  'O empréstimo consignado tem juro mais baixo. É matemática a favor.',
  'O cheque especial é juro mais alto do mercado. Foge.',
  'A taxa do rotativo do cartão pode passar de 15% ao mês.',
  'Quem entende taxa de juros não cai em propaganda enganosa.',
  'A poupança rende menos que a inflação em muitos anos. Saiba quando.',
  'O Tesouro IPCA+ acompanha a inflação. Entenda IPCA.',
  'O IGP-M reajusta aluguel. É matemática que afeta seu bolso.',
  'O IPCA é o índice oficial. Acompanhe.',
  'O CDI é o juro entre bancos. Sua referência.',
  'A taxa Selic muda a cada 45 dias. Acompanhe.',
  'O dólar oscila. Calcule média móvel para perspectiva.',
  'O ativo descorrelacionado reduz risco. Diversifique.',
  'O risco de mercado é quantificável. Não é emoção: é estatística.',
  'O VaR é Value-at-Risk. Cálculo em finanças.',
  'A tabela price tem juros embutidos pesados nas primeiras parcelas.',
  'O SAC tem amortização constante. Compare.',
  'O financiamento imobiliário é decisão de vida. Calcule duas vezes.',

  // ===== Beleza e descoberta =====
  'Quando o teorema fecha, dá um arrepio bom.',
  'Há mais beleza em uma demonstração curta que em uma longa.',
  'O ah-ha! da matemática é o melhor barato.',
  'O número e (Euler) aparece sempre que algo cresce naturalmente.',
  'O número π aparece toda vez que tem círculo escondido.',
  'O número de ouro φ aparece em concha, girassol, partenon.',
  'A sequência de Fibonacci nasce em natureza, não em livro.',
  'O triângulo de Pascal é gerador silencioso de combinatória.',
  'A simetria é a impressão digital da matemática na natureza.',
  'O fractal lembra que o complexo nasce do simples repetido.',
  'O conjunto de Mandelbrot é universo dentro do plano.',
  'A garrafa de Klein é superfície sem dentro.',
  'A faixa de Möbius vira do avesso e continua si mesma.',
  'A topologia é a geometria que ignora distância.',
  'A teoria dos grafos transforma estrutura em desenho.',
  'A teoria dos jogos transforma decisão em equação.',
  'A teoria do caos transforma imprevisibilidade em padrão.',
  'A teoria das categorias é a matemática da matemática.',
  'A geometria fractal surgiu de algo "feio" — irregularidade — e virou arte.',
  'A função zeta de Riemann esconde os primos. Ainda não revelou tudo.',
  'A hipótese de Riemann vale um milhão de dólares. E o prestígio.',
  'O último teorema de Fermat ficou aberto por 358 anos.',
  'Andrew Wiles provou Fermat em 1995. Solidão e brilho.',
  'A conjectura de Poincaré foi resolvida por Perelman. Ele recusou o prêmio.',
  'O matemático faz arte com cabeça. A arte permanece.',
  'A elegância é critério matemático. Demonstração feia é demonstração incompleta.',
  'Quem sente prazer em provar, é matemático por dentro.',
  'A primeira prova bem-feita lembra-se para sempre.',
  'O quadradinho ☐ no fim da prova é vitória silenciosa.',
  'Há matemática nas estrelas, no DNA, na onda do mar.',
  'A música é matemática que entra pelo ouvido.',
  'A pintura renascentista usou perspectiva. Geometria projetiva.',
  'A arquitetura gótica é estática matemática.',
  'A engenharia espacial é cálculo aplicado a sonho.',

  // ===== Aprender com erro =====
  'O erro corrigido é aula sua para você mesmo.',
  'Não tenha vergonha do exercício errado: ele te ensinou.',
  'Refaça o exercício errado uma semana depois. Nessa volta mora o aprendizado.',
  'Marque o erro com cor diferente. Volte nele.',
  'O erro repetido é sinal de conceito mal entendido. Não é falta de capricho.',
  'Identificar de onde veio o erro vale mais que corrigi-lo.',
  'Quem entende por que errou, não erra de novo.',
  'O caderno de erros é o melhor livro do estudante.',
  'O erro pequeno em conta esconde erro grande em conceito.',
  'Cada erro não é fracasso: é informação.',
  'Erro de sinal é técnico. Erro de método é conceitual. Distingue.',
  'O exercício errado bem analisado vale mais que dez exercícios certos.',
  'A solução errada na lousa do professor é ouro: aproveite.',
  'O colega que erra na hora certa salva sua prova.',
  'Não esconda o erro: investigue.',
  'O bom estudante mostra o erro ao professor sem vergonha.',
  'O professor bom celebra o erro corajoso, não o silêncio prudente.',
  'O exercício "fácil" que você errou é onde mora um conceito.',
  'Quando errar, não jogue a folha fora. Riscou: anota o porquê.',
  'O erro recorrente é alarme: pare e revise o conceito.',

  // ===== Confiança e coragem =====
  'Você já sabe mais do que pensa. Confie no caderno.',
  'Não é genialidade. É continuidade.',
  'Quem disse que matemática não é pra você falou besteira.',
  'O cérebro aprende matemática. É hardware antigo, mas aprende.',
  'Não há aluno "ruim em matemática". Há aluno mal apresentado.',
  'Você merece o tempo do estudo. Reserve-o.',
  'Não compare seu dia 1 com o dia 100 do outro.',
  'A vergonha de "não saber" se cura com estudo.',
  'O nervosismo da prova passa com prática.',
  'A primeira aula difícil é difícil pra todo mundo. Volte amanhã.',
  'Olha pra trás: três meses atrás, você não sabia o que sabe hoje.',
  'A confiança nasce da repetição.',
  'Você pode aprender qualquer tópico. Demanda tempo, não talento.',
  'O matemático famoso também demorou na primeira semana.',
  'O estudante que persiste vai bem. Sempre.',
  'Não tenha pressa de "ser bom". Tenha pressa de praticar.',
  'A nota não te define. O que você sabe, sim.',
  'A reprovação não é final. É reset.',
  'Aluno desmotivado é aluno mal informado. Saiba pra que serve.',
  'A primeira vez que você ensina alguém, você descobre que sabe.',
  'A insegurança vai. O conhecimento fica.',
  'Você não precisa "amar matemática". Precisa respeitá-la.',
  'O estudante que faz é mais admirável que o que entende rápido.',

  // ===== Tempo e paciência =====
  'A mente cansada não aprende. Durma.',
  'Estudar 30 minutos por dia é melhor que 5 horas no fim de semana.',
  'O Pomodoro de 25 minutos funciona. Tente.',
  'Pausa de 5 minutos a cada 25 acelera tudo.',
  'O sono consolida. Estude antes de dormir o conceito difícil.',
  'A caminhada após estudar fixa a memória.',
  'A revisão espaçada vale mais que a revisão concentrada.',
  'Repita o tópico no dia 1, dia 3, dia 7, dia 30.',
  'Esqueça o que viu hoje. Reveja amanhã. Funciona.',
  'A memorização passiva sai. A ativa fica.',
  'Faça flashcard. Anki é amigo do estudante.',
  'Resuma com palavras suas. Não copie.',
  'Explique em voz alta. Ouça-se.',
  'Ensine alguém. É o teste final.',
  'Quem ensina aprende duas vezes.',
  'Anote a dúvida. Volte nela ao final do capítulo.',
  'O estudante que coleciona dúvida cresce. O que esconde, estagna.',
  'A pergunta boa é tão valiosa quanto a resposta boa.',
  'Não aceite "é assim porque é". Pergunte por quê.',
  'Toda fórmula tem demonstração. Procure.',
  'Aprenda o "porquê" antes do "como".',

  // ===== Comunidade =====
  'O grupo de estudo dobra o rendimento.',
  'Estudar sozinho é importante. Estudar acompanhado também.',
  'Compartilhe a dúvida no grupo. Outro aluno tem a mesma.',
  'O monitor é gratuito e gosta de ensinar. Procure.',
  'O fórum online tem milhares de pessoas resolvendo. Pertença.',
  'Stack Exchange Mathematics tem ouro escondido.',
  'O canal do YouTube que explica bem vale o tempo.',
  '3Blue1Brown é arte visual da matemática.',
  'Mathologer faz prova bonita acessível.',
  'Numberphile é curiosidade pra todas as idades.',
  'O Equacionando do João Botelho é BR. Vale assistir.',
  'O Matemateca da USP tem aulas online.',
  'O canal "Matematicaê" e "Me Salva!" cobrem ENEM.',
  'O Gauss "Gauss Sumário" é brasileiro de qualidade.',
  'Encontre o canal que combina com seu cérebro. Existe.',
  'O professor que você gosta é seu aliado. Vá em aula.',
  'A faculdade boa não é só prédio. É colega.',
  'A boa conversa de corredor ensina tanto quanto a aula.',

  // ===== Tecnologia =====
  'O Wolfram Alpha resolve quase tudo. Use só pra conferir.',
  'Não use IA pra fazer exercício por você. Use pra checar.',
  'A IA explica conceito. Mas o exercício é seu.',
  'Programar é matemática que executa.',
  'Python é a língua franca da ciência de dados.',
  'NumPy é álgebra linear na prática.',
  'SciPy traz cálculo numérico em uma linha.',
  'pandas é o Excel honesto e poderoso.',
  'matplotlib desenha. Quem desenha aprende.',
  'Jupyter é caderno digital. Use.',
  'O Colab do Google é gratuito. Comece nele.',
  'GeoGebra é geometria interativa. Maravilhoso para visualizar.',
  'Desmos faz gráfico bonito em segundos.',
  'O R é estatística feita com elegância.',
  'Stata é tradição em economia aplicada.',
  'MATLAB é cálculo numérico. Caro mas poderoso.',
  'Octave é alternativa livre ao MATLAB.',
  'LaTeX é a tipografia da matemática. Aprenda.',
  'Beamer faz apresentação séria. Sem PowerPoint feio.',
  'Markdown + LaTeX em Jupyter é combinação perfeita.',
  'Git é controle de versão. Use até pra notas de estudo.',
  'O cálculo simbólico do SymPy faz álgebra exata.',
  'Mathematica é caro mas inigualável em álgebra simbólica.',
  'Maple também faz simbólico. Tradição em engenharia.',

  // ===== Brasileirismo =====
  'A matemática brasileira tem nomes grandes: Lima, Nachbin, Carvalho.',
  'O Elon Lages Lima é referência mundial em análise.',
  'Leopoldo Nachbin foi gigante da análise funcional.',
  'O Marcelo Viana é nome brasileiro vivo da matemática.',
  'O Artur Avila ganhou a medalha Fields. Brasileiro.',
  'O IMPA forma matemáticos de classe mundial em PT-BR.',
  'A USP, UNICAMP, UFRJ, UFMG têm pós em matemática top.',
  'A SBM é a Sociedade Brasileira de Matemática. Conheça.',
  'A SBPMat é onde matemáticos brasileiros se encontram.',
  'A OBMEP transformou a vida de milhares de alunos brasileiros.',
  'A medalha de bronze na OBMEP abre porta de bolsa.',
  'O PIC (Programa de Iniciação Científica Júnior) é incrível.',
  'A bolsa CNPq vale o esforço. Estude pra OBMEP.',
  'O Brasil tem matemática boa. Não somos coadjuvantes.',
  'O cariri cearense produziu Cardoso de Oliveira. Pesquise.',
  'O Pernambuco é berço de matemáticos. Lembremos do José Reis.',
  'A Bahia formou matemáticos em Salvador desde os anos 50.',
  'A Amazônia tem físicos e matemáticos exportando ciência.',
  'Brasília abriga IMPA-conferências e o ICMC-USP.',
  'O Sul tem UFRGS e UFSC com tradição forte.',
  'O Sudeste tem USP, UNICAMP, UFRJ — eixo histórico.',
  'O Nordeste cresce em pesquisa quantitativa. UFPE, UFC, UFBA.',
  'O Centro-Oeste tem UNB e UFG com programas sérios.',
  'O Norte tem UFAM e UFPA produzindo ciência.',
  'A geografia da matemática brasileira é maior que dizem.',
  'Brasileiro disciplinado bate gringo distraído. Sempre.',
  'O preconceito de "brasileiro não é bom em matemática" é mentira histórica.',
  'O ensino público brasileiro forma muito matemático. Defenda-o.',
  'A escola pública dá Olimpíada de Matemática. Confie.',
  'O ENEM bem feito vale mais que vestibular caro.',
  'Quem fez Sistema Único pode chegar onde quiser.',

  // ===== Pequenas vitórias =====
  'Resolveu o exercício 1.7 hoje? Comemora.',
  'Conseguiu desenhar o gráfico sozinho? Vitória.',
  'Lembrou da regra da cadeia sem consultar? Avanço.',
  'Acertou a integração por partes na primeira? Bom.',
  'Conseguiu provar o lema sem ler a solução? Excelente.',
  'Entendeu por que a desigualdade vira igualdade? Marca isso.',
  'Conseguiu derivar a fórmula em vez de decorar? Diferente.',
  'Fez o exercício de cabeça? Ótimo sinal.',
  'Anotou o método em uma frase? Você sabe agora.',
  'Explicou pra alguém? Perfeito.',
  'Cinco exercícios resolvidos vale celebração. De verdade.',
  'Uma página de demonstração entendida é dia bem usado.',
  'A folha cheia de rascunho é sinal de mente trabalhando.',
  'O caderno gasto é troféu silencioso.',
  'A caneta gasta vale a caneta nova.',
  'A noite mal dormida que rendeu prova boa vale a pena. Recupere amanhã.',
  'A semana que rendeu pouco mas constante é melhor que a semana de virada.',
  'O hábito vale mais que a sessão heroica.',

  // ===== Aprendizado contínuo / vida =====
  'Ninguém termina de aprender matemática. Todos avançamos.',
  'Aos 60, ainda há cálculo novo pra estudar.',
  'Aos 80, ainda dá pra aprender topologia.',
  'Aprender mantém o cérebro jovem. Estudo é saúde.',
  'Idade não impede. Vontade impede.',
  'Quem aprendeu integral aos 50 é tão capaz quanto quem aprendeu aos 20.',
  'O autodidata sério vai mais fundo que o aluno acomodado.',
  'A internet dá hoje o que a biblioteca dava há 50 anos. Use.',
  'Curso online de qualidade é grátis ou barato. Não tem desculpa.',
  'O MIT OCW disponibiliza cursos completos. Aproveite.',
  'O Coursera tem ANPEC-grade nas trilhas de Stanford e MIT.',
  'edX tem aulas de Harvard. Em inglês mas com legenda.',
  'O 3Blue1Brown ensina mais em 10 minutos do que muito livro em 100 páginas.',
  'O canal Numberphile mostra que matemática é aventura.',
  'O canal Veritasium explica ciência. Conexão total com matemática.',
  'O StatQuest do Josh Starmer é estatística clara e pop.',
  'Aprender uma área nova revigora as outras. Cruza tudo.',
  'A matemática é construída em camadas. Você adiciona uma por mês.',
  'A vida é longa o suficiente pra aprender. Comece.',

  // ===== Citações reais (autor + ano) =====
  { t: 'A matemática é o alfabeto com o qual Deus escreveu o universo.', a: 'Galileu Galilei', y: '1623' },
  { t: 'A matemática é a linguagem em que Deus escreveu o universo.', a: 'Galileu Galilei', y: '1623' },
  { t: 'Não há ramo da matemática, por mais abstrato, que um dia não possa ser aplicado a fenômenos do mundo real.', a: 'Nikolai Lobachevsky', y: '1830' },
  { t: 'A matemática é a rainha das ciências e a aritmética é a rainha da matemática.', a: 'Carl Friedrich Gauss', y: '1856' },
  { t: 'Deus criou os números inteiros; o resto é obra do homem.', a: 'Leopold Kronecker', y: '1893' },
  { t: 'A matemática pura é, em seu modo, a poesia das ideias lógicas.', a: 'Albert Einstein', y: '1935' },
  { t: 'A matemática, vista corretamente, possui não só verdade, mas suprema beleza.', a: 'Bertrand Russell', y: '1902' },
  { t: 'Um matemático que não é também um pouco poeta nunca será um matemático completo.', a: 'Karl Weierstrass', y: '1880' },
  { t: 'O essencial em matemática é fazer pouco, mas fazê-lo bem.', a: 'Carl Friedrich Gauss', y: '1820' },
  { t: 'A matemática é a ciência da ordem e da medida.', a: 'René Descartes', y: '1637' },
  { t: 'Pensei, logo existo.', a: 'René Descartes', y: '1637' },
  { t: 'A natureza está escrita em linguagem matemática.', a: 'Galileu Galilei', y: '1623' },
  { t: 'Não pretenda saber as respostas; ame as perguntas.', a: 'Rainer Maria Rilke', y: '1903' },
  { t: 'Devemos saber. Saberemos.', a: 'David Hilbert', y: '1930' },
  { t: 'Em algum lugar, algo incrível está esperando para ser descoberto.', a: 'Carl Sagan', y: '1980' },
  { t: 'A matemática é a música da razão.', a: 'James Joseph Sylvester', y: '1864' },
  { t: 'A música é o prazer que a mente humana tem ao contar sem perceber que está contando.', a: 'Gottfried Wilhelm Leibniz', y: '1712' },
  { t: 'Quem despreza a aritmética falará besteira.', a: 'John Adams', y: '1780' },
  { t: 'O verdadeiro espírito do prazer, da exaltação, do senso de ser mais que homem, encontra-se na matemática tanto quanto na poesia.', a: 'Bertrand Russell', y: '1902' },
  { t: 'A matemática é a única linguagem que todos os povos do universo entendem.', a: 'Henri Poincaré', y: '1908' },
  { t: 'O que importa não é o que sabemos, mas o que somos capazes de descobrir.', a: 'Isaac Newton', y: '1675' },
  { t: 'Se vi mais longe, foi por estar sobre os ombros de gigantes.', a: 'Isaac Newton', y: '1675' },
  { t: 'A imaginação é mais importante que o conhecimento.', a: 'Albert Einstein', y: '1929' },
  { t: 'A vida é boa por apenas duas coisas: descobrir matemática e ensinar matemática.', a: 'Siméon Poisson', y: '1830' },
  { t: 'Não me atemorizam os obstáculos; eu calculo.', a: 'Pierre-Simon Laplace', y: '1812' },
  { t: 'O que aprendemos com prazer, jamais esquecemos.', a: 'Alfred Mercier', y: '1850' },
  { t: 'O matemático é um inventor, não um descobridor.', a: 'Ludwig Wittgenstein', y: '1956' },
  { t: 'A matemática começa onde os outros já desistiram.', a: 'Paul Halmos', y: '1985' },
  { t: 'O melhor caminho é estudar pequeno e cedo.', a: 'Carl Friedrich Gauss', y: '1820' },
  { t: 'A análise matemática é, em primeiro lugar, uma forma de aprender a pensar.', a: 'Henri Poincaré', y: '1900' },
  { t: 'Os números governam o mundo.', a: 'Pitágoras', y: '≈530 a.C.' },
  { t: 'Tudo é número.', a: 'Pitágoras', y: '≈530 a.C.' },
  { t: 'Não há caminho real para a geometria.', a: 'Euclides', y: '≈300 a.C.' },
  { t: 'Dê-me um ponto de apoio e moverei o mundo.', a: 'Arquimedes', y: '≈250 a.C.' },
  { t: 'Eureka! Eureka!', a: 'Arquimedes', y: '≈250 a.C.' },
  { t: 'Não perturbe meus círculos.', a: 'Arquimedes', y: '≈212 a.C.' },
  { t: 'A geometria é o conhecimento do que é eterno.', a: 'Platão', y: '≈380 a.C.' },
  { t: 'Quem não souber geometria, que não entre.', a: 'Platão', y: '≈380 a.C.' },
  { t: 'A excelência não é um ato, mas um hábito.', a: 'Aristóteles', y: '≈340 a.C.' },
  { t: 'Conhece-te a ti mesmo.', a: 'Sócrates', y: '≈400 a.C.' },
  { t: 'O todo é maior que a soma das partes.', a: 'Aristóteles', y: '≈340 a.C.' },
  { t: 'A natureza não dá saltos.', a: 'Gottfried Wilhelm Leibniz', y: '1704' },
  { t: 'Vivemos no melhor de todos os mundos possíveis.', a: 'Gottfried Wilhelm Leibniz', y: '1710' },
  { t: 'O cálculo infinitesimal é a porta de entrada para a ciência moderna.', a: 'Joseph-Louis Lagrange', y: '1797' },
  { t: 'A geometria é a única ciência que Deus se dignou a oferecer aos homens.', a: 'Henry Brougham', y: '1820' },
  { t: 'O matemático trabalha com símbolos, mas pensa com imagens.', a: 'Henri Poincaré', y: '1908' },
  { t: 'A matemática consiste em provar a coisa mais óbvia da maneira menos óbvia.', a: 'George Pólya', y: '1945' },
  { t: 'Resolver problemas é uma habilidade prática como nadar, esquiar ou tocar piano: você só aprende imitando e praticando.', a: 'George Pólya', y: '1945' },
  { t: 'Se não consegue resolver um problema, há sempre um problema mais fácil que você consegue.', a: 'George Pólya', y: '1945' },
  { t: 'Um bom problema vale mais que mil exercícios.', a: 'George Pólya', y: '1945' },
  { t: 'Um matemático é uma máquina que transforma café em teoremas.', a: 'Alfréd Rényi', y: '1962' },
  { t: 'Meu cérebro está aberto.', a: 'Paul Erdős', y: '1980' },
  { t: 'Outro telhado, outra prova.', a: 'Paul Erdős', y: '1985' },
  { t: 'Por que números são bonitos? É como perguntar por que a Nona Sinfonia de Beethoven é bonita.', a: 'Paul Erdős', y: '1980' },
  { t: 'Um livro do qual você lê apenas o necessário, é um livro que conhece pouco.', a: 'Mark Kac', y: '1985' },
  { t: 'Lógica é a anatomia do pensamento.', a: 'John Locke', y: '1690' },
  { t: 'A matemática é o único laboratório verdadeiramente metafísico.', a: 'Henri Poincaré', y: '1903' },
  { t: 'Em matemática, o difícil é o desejo de saber.', a: 'Sophus Lie', y: '1880' },
  { t: 'A matemática é o ato de criar a partir do nada.', a: 'János Bolyai', y: '1832' },
  { t: 'O melhor caminho para entender matemática é fazer matemática.', a: 'Paul Halmos', y: '1985' },
  { t: 'Não pergunte se um problema é difícil. Pergunte se ele é interessante.', a: 'Paul Halmos', y: '1985' },
  { t: 'Para se tornar um matemático, é preciso pensar como um matemático.', a: 'Paul Halmos', y: '1985' },
  { t: 'A matemática se faz com ar e papel.', a: 'David Hilbert', y: '1900' },
  { t: 'Nenhum matemático se atreverá a colocar limites no progresso da matemática.', a: 'David Hilbert', y: '1900' },
  { t: 'A matemática é o estudo de padrões.', a: 'G. H. Hardy', y: '1940' },
  { t: 'Um matemático, como um pintor ou um poeta, é um criador de padrões.', a: 'G. H. Hardy', y: '1940' },
  { t: 'A beleza é o primeiro teste: não há lugar permanente no mundo para matemática feia.', a: 'G. H. Hardy', y: '1940' },
  { t: 'Jovens matemáticos precisam de problemas, não teorias.', a: 'Felix Klein', y: '1893' },
  { t: 'Conhecimento sem prática é como caderno sem caneta.', a: 'Confúcio', y: '≈500 a.C.' },
  { t: 'Diga-me e eu esquecerei. Mostre-me e eu lembrarei. Envolva-me e eu entenderei.', a: 'Confúcio', y: '≈500 a.C.' },
  { t: 'A jornada de mil milhas começa com um passo.', a: 'Lao Tzu', y: '≈600 a.C.' },
  { t: 'O conhecimento é poder.', a: 'Francis Bacon', y: '1597' },
  { t: 'Matemática é não-violência.', a: 'Mahatma Gandhi', y: '1925' },
  { t: 'Se você quer entender uma coisa, ensine-a.', a: 'Aristóteles', y: '≈340 a.C.' },
  { t: 'A pressa é inimiga da perfeição.', a: 'William Shakespeare', y: '1597' },
  { t: 'O sucesso é a soma de pequenos esforços repetidos dia após dia.', a: 'Robert Collier', y: '1926' },
  { t: 'Não conte os dias; faça com que os dias contem.', a: 'Muhammad Ali', y: '1975' },
  { t: 'Educação é a arma mais poderosa para mudar o mundo.', a: 'Nelson Mandela', y: '2003' },
  { t: 'Uma vez que você aprende a ler, você está livre para sempre.', a: 'Frederick Douglass', y: '1855' },
  { t: 'Se eu vi mais longe, foi por estar sobre os ombros de gigantes.', a: 'Bernard de Chartres', y: '≈1130' },
  { t: 'O aprendizado nunca esgota a mente.', a: 'Leonardo da Vinci', y: '≈1500' },
  { t: 'Estudar sem desejo arruína a memória.', a: 'Leonardo da Vinci', y: '≈1500' },
  { t: 'A simplicidade é a sofisticação suprema.', a: 'Leonardo da Vinci', y: '≈1500' },
  { t: 'O bom estudante é estudioso. O melhor é curioso.', a: 'Leopoldo Nachbin', y: '1980' },
  { t: 'Matemática se ensina fazendo.', a: 'Elon Lages Lima', y: '1995' },
  { t: 'A boa matemática é simples; o difícil é descobrir o que é simples.', a: 'Elon Lages Lima', y: '1995' },
  { t: 'O bom problema ensina mais que o bom livro.', a: 'Elon Lages Lima', y: '1995' },
  { t: 'A matemática é, ao mesmo tempo, ciência e arte.', a: 'Elon Lages Lima', y: '1995' },
  { t: 'Não decore: entenda. Não entenda só: pratique.', a: 'Elon Lages Lima', y: '1995' },
  { t: 'O bom estudante é o que faz exercícios.', a: 'Júlio César de Mello e Souza (Malba Tahan)', y: '1937' },
  { t: 'Calcular não é o fim; é a porta. O fim é compreender.', a: 'Júlio César de Mello e Souza (Malba Tahan)', y: '1937' },
  { t: 'Um problema bem proposto é meio resolvido.', a: 'Charles Kettering', y: '1947' },
  { t: 'O aprendizado é como remar contra a maré: parar é retroceder.', a: 'Confúcio', y: '≈500 a.C.' },
  { t: 'Quem caminha um pouco todo dia, viaja longe.', a: 'Henri Frédéric Amiel', y: '1882' },
  { t: 'A repetição é a mãe do estudo.', a: 'Provérbio latino', y: 'antiguidade' },
  { t: 'A pressa não é amiga do entendimento.', a: 'Provérbio brasileiro', y: 'tradicional' },
  { t: 'Quem sabe faz; quem não sabe ensina; quem nem isso sabe, ensina como ensinar.', a: 'George Bernard Shaw', y: '1903' },
  { t: 'Ensinar é aprender duas vezes.', a: 'Joseph Joubert', y: '1842' },
  { t: 'Aprenda como se você fosse viver para sempre. Viva como se fosse morrer amanhã.', a: 'Mahatma Gandhi', y: '1925' },
  { t: 'A juventude é uma doença que o tempo cura.', a: 'Provérbio popular', y: 'tradicional' },
  { t: 'O esforço diário paga juros compostos.', a: 'Charlie Munger', y: '1995' },
  { t: 'Invista em você. É o ativo de maior retorno.', a: 'Warren Buffett', y: '2008' },
  { t: 'Quem não estuda história, repete-a.', a: 'George Santayana', y: '1905' },
  { t: 'O hábito faz o monge.', a: 'Provérbio brasileiro', y: 'tradicional' },
  { t: 'Devagar se vai ao longe.', a: 'Provérbio brasileiro', y: 'tradicional' },
  { t: 'Água mole em pedra dura, tanto bate até que fura.', a: 'Provérbio brasileiro', y: 'tradicional' },
  { t: 'O matemático é o conquistador do não-óbvio.', a: 'Henri Poincaré', y: '1908' },
  { t: 'O fim da educação é fazer o homem desejar a verdade e amá-la.', a: 'Manuel Kant', y: '1781' },
  { t: 'Matemática é a ciência das relações invariantes.', a: 'Henri Poincaré', y: '1903' },
  { t: 'Estatística é a gramática da ciência.', a: 'Karl Pearson', y: '1892' },
  { t: 'Probabilidade é o senso comum reduzido a cálculo.', a: 'Pierre-Simon Laplace', y: '1814' },
  { t: 'O acaso, em última análise, é o resultado de leis que não conhecemos.', a: 'Pierre-Simon Laplace', y: '1814' },
  { t: 'A natureza falou: ouvimos, mas não respondemos com matemática suficiente.', a: 'Henri Poincaré', y: '1903' },
  { t: 'A matemática é a chave de ouro com a qual abrimos o universo.', a: 'Opal Whiteley', y: '1920' },
  { t: 'Em matemática, a ciência da quantidade, mil é apenas um número entre outros.', a: 'Bertrand Russell', y: '1903' },
  { t: 'Quem ousa, aprende.', a: 'Provérbio popular', y: 'tradicional' },
  { t: 'Pensar é o trabalho mais difícil — por isso tão pouca gente o faz.', a: 'Henry Ford', y: '1922' },
  { t: 'Hoje é o melhor dia para começar.', a: 'Provérbio chinês', y: 'tradicional' },
  { t: 'Quem semeia hoje, colhe amanhã.', a: 'Provérbio brasileiro', y: 'tradicional' },
  { t: 'Não há atalhos para qualquer lugar que valha a pena chegar.', a: 'Beverly Sills', y: '1985' },
  { t: 'A excelência é uma viagem, não um destino.', a: 'Tony Robbins', y: '1991' },
  { t: 'Conhecimento é a viagem, não o destino.', a: 'Zig Ziglar', y: '1980' },
  { t: 'A matemática é mais uma questão de paciência do que de inteligência.', a: 'Bertrand Russell', y: '1902' },
  { t: 'A teoria sem prática é estéril; a prática sem teoria é cega.', a: 'Immanuel Kant', y: '1781' },
  { t: 'O hábito de ler é o único prazer em que não há culpa.', a: 'Vladimir Nabokov', y: '1955' },
  { t: 'A repetição cria mestres.', a: 'Bruce Lee', y: '1971' },
  { t: 'Nada de prestígio: faça o trabalho.', a: 'Richard Hamming', y: '1986' },
  { t: 'O importante é aprender a aprender.', a: 'Richard Hamming', y: '1986' },
  { t: 'O excesso de conhecimento sem prática estraga o estudante.', a: 'Sêneca', y: '60' },
  { t: 'Estudar matemática é como pedalar: parou, caiu.', a: 'Provérbio acadêmico', y: 'tradicional' },
  { t: 'A perseverança vence a sorte.', a: 'Provérbio brasileiro', y: 'tradicional' },
  { t: 'O caminho se faz caminhando.', a: 'Antonio Machado', y: '1912' },
  { t: 'A vida não premia inteligência: premia trabalho.', a: 'Stephen King', y: '2000' },
  { t: 'Comece pequeno. Pense grande. Aja todo dia.', a: 'Robin Sharma', y: '2010' },
  { t: 'A constância é mais forte que a violência.', a: 'Plutarco', y: '≈100' },
  { t: 'Sem matemática, a ciência seria cega; sem ciência, a matemática seria muda.', a: 'Henri Poincaré', y: '1908' },
  { t: 'Calcular é raciocinar; raciocinar é calcular.', a: 'Thomas Hobbes', y: '1651' },
  { t: 'A geometria existe em toda parte.', a: 'Johannes Kepler', y: '1619' },
  { t: 'O universo é um livro escrito em matemática.', a: 'Galileu Galilei', y: '1623' },
  { t: 'Ler bons livros é como conversar com as melhores mentes do passado.', a: 'René Descartes', y: '1637' },
  { t: 'Toda nossa ciência, comparada à realidade, é primitiva e infantil — ainda assim, é a coisa mais preciosa que temos.', a: 'Albert Einstein', y: '1930' },
  { t: 'A coisa mais incompreensível do mundo é que ele seja compreensível.', a: 'Albert Einstein', y: '1936' },
  { t: 'Quem não sabe matemática não sabe nada.', a: 'Roger Bacon', y: '1267' },
  { t: 'A matemática é o instrumento dos engenheiros do mundo.', a: 'Lord Kelvin', y: '1880' },
  { t: 'Quando podemos medir, sabemos algo. Quando não podemos, nosso conhecimento é magro.', a: 'Lord Kelvin', y: '1883' },
  { t: 'A demonstração é o que distingue a matemática das outras ciências.', a: 'Bertrand Russell', y: '1903' },
  { t: 'Ousadia, mais ousadia, sempre ousadia.', a: 'Georges Danton', y: '1792' },
  { t: 'Seja o aluno do qual seu professor se orgulharia em vinte anos.', a: 'Provérbio acadêmico', y: 'tradicional' },
  { t: 'A boa pergunta vale mais que a boa resposta.', a: 'Provérbio chinês', y: 'tradicional' },
  { t: 'O matemático profundo é o que faz uma pergunta antes obscura tornar-se óbvia.', a: 'Pierre Deligne', y: '1990' },
  { t: 'A matemática é o microscópio com que vemos o invisível.', a: 'Provérbio acadêmico', y: 'tradicional' },
  { t: 'A elegância é a aliança da precisão com a simplicidade.', a: 'Henri Poincaré', y: '1908' },
  { t: 'Ler matemática é estudar matemática.', a: 'Paul Halmos', y: '1985' },
  { t: 'Não diga "eu não consigo". Diga "ainda não consegui".', a: 'Carol Dweck', y: '2006' },
  { t: 'O cérebro é músculo. Treine.', a: 'Carol Dweck', y: '2006' },
  { t: 'Mentalidade de crescimento muda a vida do estudante.', a: 'Carol Dweck', y: '2006' },
  { t: 'O melhor matemático é aquele que ainda lembra de ter sido aluno.', a: 'Provérbio acadêmico', y: 'tradicional' },
  { t: 'O passado é a única fonte de futuro.', a: 'Provérbio sufi', y: 'tradicional' },
  { t: 'Quem se compromete com o estudo, compromete-se consigo mesmo.', a: 'Provérbio acadêmico', y: 'tradicional' },
  { t: 'O mais importante na educação não é a quantidade, mas a qualidade.', a: 'José Saramago', y: '2004' },
  { t: 'Aprender é o único jeito de amadurecer.', a: 'Paulo Freire', y: '1996' },
  { t: 'Ensinar não é transferir conhecimento, mas criar possibilidades para sua produção.', a: 'Paulo Freire', y: '1996' },
  { t: 'A leitura do mundo precede a leitura da palavra.', a: 'Paulo Freire', y: '1989' },
  { t: 'Ninguém educa ninguém; ninguém se educa sozinho. Os homens se educam em comunhão.', a: 'Paulo Freire', y: '1968' },
  { t: 'A educação é um ato de amor, por isso, um ato de coragem.', a: 'Paulo Freire', y: '1996' },
  { t: 'A pedagogia do oprimido começa com a alfabetização do mundo.', a: 'Paulo Freire', y: '1968' },

  // ===== Mais originais — específicos por tópico =====
  'Quando o limite dá indeterminação, manipule. Não chute.',
  'Toda derivada é taxa de variação. Pense em "por unidade".',
  'A integral de Riemann é soma infinita. Pense em soma de fatias.',
  'A integral imprópria pede limite. Não esqueça.',
  'A regra de L\'Hôpital pede 0/0 ou ∞/∞. Verifique a forma.',
  'Não use L\'Hôpital cegamente. Às vezes não simplifica.',
  'Taylor é aproximação local. Bom em vizinhança pequena.',
  'A série binomial generaliza Pascal para expoentes não inteiros.',
  'A função exponencial cresce mais rápido que qualquer polinômio.',
  'O logaritmo cresce mais devagar que qualquer raiz.',
  'A função arctan cresce e estabiliza em π/2.',
  'Uma reta tangente toca em um ponto. Uma reta normal é perpendicular.',
  'A taxa instantânea é o limite da taxa média.',
  'O teorema do valor médio garante: existe ponto onde a derivada é a taxa média.',
  'Rolle é caso particular do TVM: derivada zera em algum lugar.',
  'A continuidade exige limite igual ao valor da função.',
  'Pulo na função quebra continuidade. Verifique.',
  'A descontinuidade removível é "buraco". Pode ser tampada.',
  'Descontinuidade essencial não tem cura.',
  'Limite lateral pode existir e o limite bilateral não.',
  'A regra do produto não é d(uv) = du dv. É d(uv) = u dv + v du.',
  'A regra do quociente é (vu\' − uv\')/v². Decore o sinal.',
  'A derivada do seno é cosseno. A derivada do cosseno é menos seno.',
  'A derivada de e^x é e^x. Mágica e simples.',
  'A derivada de ln x é 1/x. Decore.',
  'A derivada de a^x é a^x · ln a. Não esqueça do ln.',
  'A integral indefinida sempre carrega + C.',
  'A integral definida não carrega C: o C cancela.',
  'A área sob a curva é a integral definida (quando f é positiva).',
  'O volume de revolução usa π ∫ r² dx.',
  'Comprimento de arco usa ∫ √(1 + (f\')²) dx.',
  'Em coordenadas polares, área é ½ ∫ r² dθ.',
  'A função par é simétrica ao eixo y.',
  'A função ímpar é simétrica à origem.',
  'A integral de função ímpar em intervalo simétrico é zero.',
  'A função periódica repete. Período é menor T tal que f(x+T) = f(x).',
  'Sin e cos têm período 2π. Tan tem π.',
  'A inversa de seno é arcsen, com domínio [−1, 1].',
  'A inversa de tangente é arctan, definida em ℝ.',
  'Identidades trigonométricas são tabuada do triângulo.',
  'sin² + cos² = 1. A identidade pitagórica.',
  'tan² + 1 = sec². Lembre.',
  '1 + cot² = csc². Lembre também.',
  'sin(a+b) = sin a cos b + cos a sin b.',
  'cos(a+b) = cos a cos b − sin a sin b.',
  'A duplicação: sin 2x = 2 sin x cos x.',
  'A duplicação do cosseno tem três formas. Saiba escolher.',
  'A meia-volta: cos²(x/2) = (1+cos x)/2.',
  'O produto em soma usa identidades de prosthaphaeresis.',
  'Lei dos senos: a/sin A = 2R (R = raio circunscrito).',
  'Lei dos cossenos generaliza Pitágoras.',
  'Em triângulo retângulo, sin = oposto/hipotenusa.',
  'cos = adjacente/hipotenusa. tan = oposto/adjacente.',
  'O círculo trigonométrico tem raio 1. Use sempre.',
  'Em coordenadas, (cos θ, sin θ) é ponto no círculo unitário.',
  'A equação geral da reta é ax + by + c = 0.',
  'A reta vertical não tem coeficiente angular definido.',
  'A reta y = mx + b tem coeficiente angular m e linear b.',
  'Duas retas paralelas têm mesmo m. Perpendiculares têm m₁·m₂ = −1.',
  'A distância de ponto a reta é |ax₀+by₀+c|/√(a²+b²).',
  'A circunferência tem equação (x−a)² + (y−b)² = r².',
  'A elipse tem dois focos. A soma das distâncias é constante.',
  'A hipérbole tem dois focos. A diferença das distâncias é constante.',
  'A parábola tem foco e diretriz. Pontos equidistantes a ambos.',
  'Excentricidade 0: círculo. Entre 0 e 1: elipse. 1: parábola. Maior que 1: hipérbole.',
  'Vetor (a, b) tem módulo √(a²+b²).',
  'Soma de vetores é "ponta a cauda".',
  'Produto escalar mede projeção. u·v = |u||v|cos θ.',
  'Produto escalar zero: vetores ortogonais.',
  'Produto vetorial dá perpendicular. Tem orientação (regra da mão direita).',
  'Determinante 2x2 é ad − bc.',
  'Determinante 3x3 expande por Sarrus ou cofator.',
  'Determinante zero: matriz singular, não tem inversa.',
  'Sistema com determinante zero pode ter solução, infinitas ou nenhuma.',
  'Cramer: solução existe se determinante da matriz é não nulo.',
  'Eliminação de Gauss é o método universal. Aprenda.',
  'Posto de matriz é número de linhas independentes.',
  'Posto + nulidade = número de colunas.',
  'Autovalor é escalar λ tal que Av = λv para algum v ≠ 0.',
  'Autovetor é o vetor que só sofre escala (não rotação).',
  'Matriz simétrica tem autovalores reais.',
  'Matriz ortogonal preserva norma.',
  'Mudança de base é recoordinatizar o mesmo vetor.',
  'A base canônica é só uma das infinitas bases.',
  'Espaço vetorial tem operações fechadas e propriedades de campo.',
  'Subspaço é subconjunto fechado nas operações.',
  'Combinação linear é soma escalada.',
  'Linearmente independentes: nenhuma combinação não trivial dá zero.',
  'Dimensão é tamanho da base.',
  'Núcleo é onde a transformação manda em zero.',
  'Imagem é onde a transformação chega.',

  // ===== Probabilidade e estatística =====
  'Probabilidade é a chance esperada, antes do experimento.',
  'Frequência relativa é a chance observada, depois do experimento.',
  'A lei dos grandes números: frequência tende à probabilidade.',
  'Independência: P(A∩B) = P(A)·P(B).',
  'Mutuamente exclusivos: P(A∪B) = P(A) + P(B).',
  'Probabilidade condicional: P(A|B) = P(A∩B)/P(B).',
  'Teorema de Bayes inverte a condicional. Saiba usar.',
  'O teorema de Bayes é a base da inferência moderna.',
  'A distribuição normal aparece pela soma de muitos pequenos efeitos.',
  'O teorema central do limite faz a normal aparecer.',
  'Uma amostra grande é melhor que uma amostra precisa pequena.',
  'A média amostral converge para a média populacional.',
  'Variância mede dispersão ao quadrado.',
  'Desvio padrão é raiz da variância. Mesma unidade dos dados.',
  'A mediana é robusta a outliers. Use quando há cauda.',
  'A média é sensível a outliers. Cuidado.',
  'A moda é o valor mais frequente. Pode ter mais de uma.',
  'Quartil divide em quatro partes iguais.',
  'O boxplot mostra mediana, quartis e outliers de uma vez.',
  'Histograma mostra distribuição. Boxplot resume.',
  'A regressão minimiza soma de quadrados dos resíduos.',
  'O coeficiente de determinação R² mede ajuste.',
  'Correlação não implica causalidade.',
  'Pearson mede correlação linear. Spearman mede monotônica.',
  'O p-valor é probabilidade do dado dado o nulo. Não é "probabilidade do nulo".',
  'Significância estatística não é significância prática.',
  'Erro tipo I: rejeitar nulo verdadeiro. Tipo II: aceitar nulo falso.',
  'O poder do teste é 1 menos probabilidade do erro tipo II.',
  'Intervalo de confiança contém o parâmetro com tal frequência sob amostragem repetida.',
  'O bootstrap é amigo. Aprenda.',
  'Validação cruzada evita overfitting.',
  'O viés-variância tradeoff é central em ML.',
  'Modelo simples generaliza melhor que modelo complexo, em geral.',
  'Overfitting é decorar amostra. Subajuste é não aprender.',
  'Regularização (L1, L2) controla complexidade.',
  'Lasso (L1) faz seleção de variáveis.',
  'Ridge (L2) reduz coeficientes mas não zera.',
  'Random Forest agrega muitas árvores. Reduz variância.',
  'Gradient Boosting é sequencial. Cada árvore corrige erros da anterior.',
  'Redes neurais aprendem hierarquia de features.',
  'Backpropagation é regra da cadeia em escala.',
  'Otimização convexa tem mínimo global. Não-convexa, mínimo local.',
  'Gradiente descendente: ande na direção oposta ao gradiente.',
  'Taxa de aprendizado importa. Muito alta diverge. Muito baixa demora.',
  'Adam é otimizador padrão. Mas SGD com momentum também serve.',

  // ===== Lógica e demonstração =====
  'P implica Q: se P então Q. Não é P se e somente se Q.',
  'Contrapositiva equivale ao original. Use quando útil.',
  'Inversa: ¬P → ¬Q. Recíproca: Q → P. Não equivalem ao original.',
  'Demonstração direta é a mais simples.',
  'Por absurdo: assuma o contrário, chegue a impossível.',
  'Por indução: base, hipótese, passo. Triângulo de ferro.',
  'Indução forte: usa hipótese para todos os k ≤ n, não só k = n.',
  'Princípio da casa dos pombos: n+1 pombos em n casas, alguma casa tem dois.',
  'Demonstração por construção: exiba o objeto, mostre que serve.',
  'Demonstração por exaustão: cubra todos os casos, finitos.',
  'Conjuntos: ⊂ é "contido". ⊆ é "contido ou igual".',
  'Vazio é subconjunto de qualquer conjunto.',
  'União: pelo menos um. Interseção: ambos.',
  'Diferença A−B: em A mas não em B.',
  'Complemento depende do universo. Defina o universo.',
  'Lei de De Morgan: (A∪B)\' = A\' ∩ B\'. (A∩B)\' = A\' ∪ B\'.',
  'Distributivas: A∩(B∪C) = (A∩B)∪(A∩C). E vice-versa.',
  'Cardinal: |A∪B| = |A| + |B| − |A∩B|.',
  'Princípio da inclusão-exclusão generaliza para n conjuntos.',
  'Quantificadores: ∀ (todo) e ∃ (existe). Atenção à ordem.',
  'A negação de ∀x P(x) é ∃x ¬P(x).',
  'A negação de ∃x P(x) é ∀x ¬P(x).',
  'Função injetora: distintos vão para distintos.',
  'Sobrejetora: imagem é todo o contradomínio.',
  'Bijetora: injetora e sobrejetora. Tem inversa.',
  'Composição preserva injetividade e sobrejetividade.',
  'A inversa só existe para bijetoras.',
  'Aritmética modular: a ≡ b (mod n) se n divide (a − b).',
  'Aritmética modular é a base de criptografia.',
  'O pequeno teorema de Fermat: a^(p−1) ≡ 1 (mod p), se p primo e p não divide a.',
  'Euler generaliza Fermat com a função totiente.',
  'O algoritmo de Euclides acha mdc rapidamente.',
  'O lema de Bezout: existe combinação inteira ax + by = mdc(a,b).',
  'Teorema chinês do resto: sistema modular tem solução única se módulos são coprimos.',
  'Um número primo só tem dois divisores positivos.',
  'O teorema fundamental da aritmética: fatoração única em primos.',
  'Há infinitos primos (Euclides).',
  'A distribuição dos primos é tema de pesquisa há séculos.',
  'O teorema dos números primos: π(n) ~ n/ln n.',

  // ===== Mais cheer =====
  'Você é maior que sua última prova.',
  'A nota baixa de hoje não dita o futuro.',
  'O concurso só pede dedicação. E dedicação você tem.',
  'Quem chega tarde mas chega, chega.',
  'Sua mãe vai se orgulhar quando você passar. Vamos.',
  'Seu pai vai te ver formado. Vamos.',
  'Seu avô vai te ver com diploma. Vamos.',
  'O Brasil precisa de gente que sabe matemática. Você é uma delas.',
  'Estude pela sua família. Estude por você. Estude.',
  'A bolsa é sua, basta um pouco mais de esforço.',
  'O estágio bom procura quem sabe matemática. Esteja pronto.',
  'O primeiro emprego de qualidade vem de quem se preparou.',
  'A entrevista pega quem sabe contar e raciocinar.',
  'O recrutador valoriza quem fez OBMEP, mesmo sem medalha.',
  'Listar prêmio em currículo conta. Vá fazer.',
  'A bolsa do PIBIC abre porta de pós.',
  'A monitoria ensina e paga. Inscreva-se.',
  'Ser monitor de cálculo é o melhor reforço para você.',
  'Quem ensina entende dobrado.',
  'A iniciação científica jovem pode mudar sua trajetória.',
  'Profissão não escolhida na adolescência? Sem problema. Estude o tronco comum.',
  'O básico é tronco comum. Cálculo, álgebra, estatística.',
  'A indecisão é normal. A inação é fatal.',
  'Não saber qual carreira ainda é OK. Estudar matemática não é.',
  'O tronco quantitativo abre 50 carreiras.',
  'Engenharia, economia, administração quantitativa, ciência da computação, ciência atuarial: todas pedem o mesmo cálculo.',

  // ===== Sentimento / autoconfiança =====
  'Acordou cedo pra estudar? Bom dia, herói.',
  'Estudou no fim de semana? Você é o tipo que vence.',
  'Madrugou na véspera da prova? Aceitável uma vez. Não vire hábito.',
  'Você tem o direito de estar cansado. Volte amanhã.',
  'A pressão da família é pesada. Mas o esforço é seu, não delas.',
  'Cuide da saúde mental. Cérebro cansado não estuda.',
  'Caminhe. Beba água. Coma direito. Estude.',
  'Não estude doente. Cuide do corpo, depois volte.',
  'Não compare seu sono com o do colega. Dorme suas 8h.',
  'O burnout é real. Pause antes de quebrar.',
  'Se você tem ansiedade, busque ajuda. Não é vergonha.',
  'O psicólogo é aliado do estudante, não inimigo.',
  'A meditação ajuda. Cinco minutos por dia.',
  'A respiração lenta acalma a mente antes da prova.',
  'O exercício físico libera endorfina. Estudar fica mais fácil.',
  'Toque um instrumento, dance, faça arte. Cérebro precisa de variedade.',
  'O estudante completo é mais que aluno: é pessoa.',
  'Saúde, família, amigos, estudo. Equilibre.',
  'Você não é só sua prova. Mas a prova ajuda você a ser mais.',
  'Você é capaz. Sempre foi. Sempre será.',

  // ===== Mais originais — decidi expandir esse bloco =====
  'Cinco minutos hoje valem mais que cinquenta amanhã.',
  'A constância faz o gênio. O gênio é constância pintada de cor.',
  'Não diga "eu não sei". Diga "ainda não sei".',
  'O esforço hoje compra futuro caro.',
  'Sua versão de seis meses atrás te aplaude.',
  'Sua versão de seis meses no futuro depende do hoje.',
  'O matemático aposentado ainda estuda matemática. Por amor.',
  'A matemática é hobby honesto.',
  'A matemática nunca decepciona. Você decepciona a você mesmo se não estuda.',
  'O exercício esquecido cobra na hora da prova.',
  'O caderno organizado é metade da memória.',
  'A folha amassada é estudo de verdade.',
  'O capricho ajuda. Mas a substância é mais importante.',
  'O bom matemático é, antes de tudo, paciente.',
  'Quem corre demais tropeça em ε.',
  'A pressa atropela demonstração. Devagar.',
  'Aprender é colar peças. Algumas grandes, outras pequenas.',
  'A peça pequena que faltava te trava por dois dias. Volte ao livro.',
  'O capítulo que você pulou volta na avaliação. Faça os pulados.',
  'Não pule capítulo. Cada um sustenta o seguinte.',
  'O conceito mal entendido cria buraco. Tape antes que cresça.',
  'Os erros se acumulam quando o conceito não é firme.',
  'Reveja o conceito antes do exercício difícil.',
  'O exercício revela o conceito mal sabido.',
  'Cinco exercícios por dia, em cinco anos, são quase 9.000.',
  'Ninguém faz 9.000 exercícios sem virar bom.',
  'A repetição revela padrão. O padrão revela teoria.',
  'A teoria sem exercício vira fumaça.',
  'O exercício sem teoria vira esforço gasto à toa.',
  'Combine os dois. Sempre.',
  'Faça do estudo um ritual.',
  'Mesmo horário, mesmo lugar. Mente entende.',
  'Aprenda a treinar a si mesmo.',
  'O autoaprendizado é o aprendizado mais valioso.',
  'A internet é a maior biblioteca da história. Use bem.',
  'Não reclame de "não ter aula". Você tem todo o conhecimento do mundo no celular.',
  'A geração que tem acesso ilimitado à informação é a sua. Aproveite.',
  'O aluno do interior pode aprender o que o aluno da capital aprende.',
  'O CEP não escolhe quem aprende. Vontade escolhe.',
  'A maior universidade hoje é seu fone com YouTube e PDF.',
  'Não tem internet em casa? Estude na biblioteca pública.',
  'Não tem biblioteca? Estude na escola depois da aula.',
  'Não tem nada? Estude no caderno. O caderno basta.',
  'Lápis e papel ainda são as melhores ferramentas.',
  'O computador ajuda. Mas o lápis é insubstituível.',
  'Faça conta no papel antes de fazer no Excel.',
  'Quem só usa calculadora esquece o método.',
  'A calculadora confere. Não faz por você.',
  'Quem entende, calcula. Quem não entende, aperta.',
  'O método importa mais que o resultado certo.',
  'O método errado com resultado certo é sorte.',
  'O método certo com resultado errado é detalhe técnico. Conserte.',
  'Mostre o método. O método mostra que você sabe.',
  'Resposta sem método não vale nota cheia.',
  'Toda passagem tem justificativa. Mostre.',
  'Aprenda a escrever matemática. Como se ensinasse.',
  'A boa redação matemática é honesta.',
  'Não esconda passagem por preguiça. Escreva.',
  'O leitor da sua solução é seu colega futuro. Ele agradece a clareza.',

  // ===== Curiosidades motivadoras =====
  'O livro de Euclides ensinou geometria por 2.000 anos. Fundamental.',
  'Newton inventou o cálculo aos 23 anos. Em casa, pela peste.',
  'Gauss resolveu a soma de 1 a 100 aos 7 anos.',
  'Évariste Galois revolucionou a álgebra antes dos 21.',
  'Sofia Kovalevskaya foi a primeira mulher PhD em matemática (1874).',
  'Ada Lovelace escreveu o primeiro algoritmo, em 1843.',
  'Maryam Mirzakhani foi a primeira mulher a ganhar a Fields, em 2014.',
  'Karen Uhlenbeck foi a primeira mulher Abel, em 2019.',
  'Emmy Noether mudou álgebra abstrata. Século 20.',
  'Srinivasa Ramanujan, autodidata indiano, descobriu fórmulas que ninguém imaginava.',
  'Alan Turing fundou a ciência da computação. Matemático.',
  'John von Neumann construiu a arquitetura de computador moderna.',
  'Andrew Wiles passou 7 anos isolado provando Fermat.',
  'Grigori Perelman recusou US$ 1 milhão para ficar na floresta.',
  'Terence Tao começou a universidade aos 9 anos.',
  'Maryna Viazovska resolveu empacotamento em 8 dimensões. Ganhou a Fields em 2022.',
  'Brasileiro Artur Avila ganhou a Fields em 2014. Orgulho.',
  'O computador da NASA na missão Apollo tinha menos potência que seu celular.',
  'A criptografia que protege seu PIX é teoria dos números pura.',
  'A primeira foto de buraco negro foi reconstrução matemática.',
  'O Google nasceu de álgebra linear (PageRank).',
  'O Netflix usa filtragem colaborativa, que é matemática.',
  'O Spotify recomenda com base em fatoração matricial.',
  'Toda IA que você usa é matemática.',
  'Cada like que você dá vira número numa equação de recomendação.',
  'O algoritmo do TikTok é matemática estocástica.',
  'A imagem que você tira tem matrizes por trás.',
  'O mapa do GPS roda equações de relatividade.',
  'O semáforo da sua cidade é otimizado com pesquisa operacional.',
  'A vacina foi calibrada com modelos matemáticos.',
  'O médico que dosou seu remédio usou farmacocinética. Matemática.',
  'Em pandemia, modelos SIR salvam vidas.',
  'A engenharia de uma ponte usa cálculo estrutural.',
  'O avião voa com aerodinâmica. Equações de Navier-Stokes.',
  'Foguete sobe com cálculo. Sem cálculo, sem espaço.',
  'A energia nuclear é matemática controlada.',
  'A previsão do clima usa supercomputador rodando matemática.',
  'O smartphone tem cinco PhDs em matemática nele.',
  'Saiba que matemática mora em tudo. Vai ser difícil parar de estudar.',

  // ===== Frases finais =====
  'Cada dia de estudo é depósito no banco do seu futuro.',
  'O conhecimento é a única herança que ninguém te tira.',
  'Quem estuda hoje, decide amanhã.',
  'Você está mais perto do que pensa.',
  'Seu primeiro teorema entendido é o início de uma vida nova.',
  'Bem-vindo ao Clube. Aqui a gente estuda junto.',
  'Hoje é um bom dia para abrir o caderno.',
  'Vamos.',

  // ===== Sementes adicionais (idade não importa) =====
  'Tenho 50 anos, devo estudar Matemática? Sim.',
  'Tenho 60 anos, devo estudar Matemática? Sim.',
  'Tenho 70 anos, devo estudar Matemática? Sim. Cérebro velho aprende quando treinado.',
  'Tenho 40 anos, está tarde pra Matemática? Não. Está cedo.',
  'Tenho 30 anos, mudei de área, posso aprender Cálculo? Pode. Comece hoje.',
  'Tenho 18 anos, tenho a vida inteira pela frente. Estude.',
  'Tenho 15 anos, estou no momento certo. Não desperdice.',
  'Tenho 12 anos, Matemática é minha amiga. Continue assim.',

  // ===== Bernard Cornwell — Saxon Stories (Uhtred de Bebbanburg) =====
  { t: 'Wyrd bið ful aræd — o destino é inexorável. Mas o estudo de hoje muda o destino de amanhã.', a: 'Bernard Cornwell (Saxon Stories)', y: '2004' },
  { t: 'O destino governa tudo. E o destino do estudante disciplinado é vencer.', a: 'Bernard Cornwell (Saxon Stories)', y: '2004' },
  { t: 'Não há glória sem treino. O herói é o que treinou na chuva.', a: 'Bernard Cornwell (Saxon Stories)', y: '2005' },
  { t: 'Dane sem espada é dane morto. Estudante sem caderno é estudante sem rumo.', a: 'Bernard Cornwell (Saxon Stories)', y: '2006' },
  { t: 'A muralha de escudos só vence se cada homem segura o seu. Estude o seu trecho da matéria.', a: 'Bernard Cornwell (Saxon Stories)', y: '2007' },
  { t: 'Beocca dizia que Deus é tabuleiro de xadrez. Eu digo que matemática é o mesmo.', a: 'Bernard Cornwell (Saxon Stories)', y: '2008' },
  { t: 'Um homem é o que faz, não o que pensa em fazer. Faça os exercícios.', a: 'Bernard Cornwell (Saxon Stories)', y: '2010' },

  // ===== Bernard Cornwell — Sharpe Series =====
  { t: 'Sharpe não nasceu oficial. Subiu pela espada e pelo trabalho. Suba pelo estudo.', a: 'Bernard Cornwell (Sharpe Series)', y: '1981' },
  { t: 'Patrick Harper dizia: "Vai um pouquinho mais." Vai. Mais um exercício.', a: 'Bernard Cornwell (Sharpe Series)', y: '1982' },
  { t: 'A baioneta cega mata. A pena cega também. Afie a sua.', a: 'Bernard Cornwell (Sharpe Series)', y: '1983' },
  { t: 'O 95º regimento de fuzileiros treinava enquanto os outros descansavam. Treine.', a: 'Bernard Cornwell (Sharpe Series)', y: '1981' },
  { t: 'Sharpe dizia que disciplina vence sangue azul. Em estudo, vale igual.', a: 'Bernard Cornwell (Sharpe Series)', y: '1985' },

  // ===== George R. R. Martin — A Song of Ice and Fire =====
  { t: 'Um leitor vive mil vidas antes de morrer. Quem nunca lê, vive apenas uma.', a: 'George R. R. Martin (A Dance with Dragons)', y: '2011' },
  { t: 'Uma mente precisa de livros como uma espada precisa de uma pedra de amolar.', a: 'George R. R. Martin (A Game of Thrones, Tyrion Lannister)', y: '1996' },
  { t: 'Ler é a arma mais poderosa contra a estupidez do mundo.', a: 'George R. R. Martin (paráfrase)', y: '2011' },
  { t: 'O inverno está chegando. E o inverno premia quem se preparou.', a: 'George R. R. Martin (A Game of Thrones, Stark)', y: '1996' },
  { t: 'Há apenas uma coisa que dizemos à Morte: hoje não. Diga isso ao desânimo: hoje não.', a: 'George R. R. Martin (A Game of Thrones, Syrio Forel)', y: '1996' },
  { t: 'Todo voo começa com uma queda.', a: 'George R. R. Martin (A Storm of Swords)', y: '2000' },
  { t: 'O homem corajoso não é o que não tem medo: é o que age apesar dele.', a: 'George R. R. Martin (paráfrase, Eddard Stark)', y: '1996' },
  { t: 'Hodor.', a: 'George R. R. Martin (A Storm of Swords)', y: '2000' },
  { t: 'O conhecimento é uma arma. Eu me armo bem antes de entrar na batalha.', a: 'George R. R. Martin (A Storm of Swords, Tyrion Lannister)', y: '2000' },
  { t: 'A noite é escura e cheia de exercícios. Resolva-os.', a: 'paráfrase de Melisandre', y: '2011' },
  { t: 'O homem que diz "não posso" está condenado a ver o "podia ter".', a: 'George R. R. Martin (paráfrase)', y: '2005' },

  // ===== Robert Jordan / Brandon Sanderson — Wheel of Time =====
  { t: 'A Roda gira como a Roda quer. Mas o estudante decide o quanto remar.', a: 'Robert Jordan (The Wheel of Time)', y: '1990' },
  { t: 'O carvalho luta com o vento e quebra. O salgueiro verga quando deve, e sobrevive.', a: 'Robert Jordan (The Wheel of Time)', y: '1990' },
  { t: 'A morte é leve como uma pena, o dever pesa como uma montanha.', a: 'Robert Jordan (The Wheel of Time)', y: '1990' },
  { t: 'O tempo é um rio. A memória, uma neblina. O caderno, uma jangada.', a: 'Robert Jordan (The Wheel of Time, paráfrase)', y: '1992' },
  { t: 'Lan Mandragoran ensinou Rand a empunhar a espada. O caderno empunha você.', a: 'Robert Jordan (The Eye of the World)', y: '1990' },
  { t: 'Aiel Saying: "Sleep is a death without value." Estude antes de dormir.', a: 'Robert Jordan (The Shadow Rising)', y: '1992' },
  { t: 'Há sempre outra dança, sempre outra batalha, sempre outro problema. Encare.', a: 'Robert Jordan (The Wheel of Time, paráfrase)', y: '1995' },
  { t: 'Brandon Sanderson terminou o que Jordan começou. Você termina o que começou também.', a: 'Brandon Sanderson (A Memory of Light)', y: '2013' },
  { t: 'O homem importante é o que se levantou da queda mais uma vez que caiu.', a: 'Brandon Sanderson (paráfrase)', y: '2010' },
  { t: 'Jornada antes de destino. Estude antes da prova.', a: 'Brandon Sanderson (Stormlight Archive)', y: '2010' },
  { t: 'Vida antes de morte. Força antes da fraqueza. Jornada antes do destino.', a: 'Brandon Sanderson (The Way of Kings, Idéias dos Cavaleiros Radiantes)', y: '2010' },

  // ===== Outros autores literários (motivação e disciplina) =====
  { t: 'O segredo do sucesso é a constância no propósito.', a: 'Benjamin Disraeli', y: '1870' },
  { t: 'Não importa o quão devagar você vai, contanto que não pare.', a: 'Confúcio', y: '≈500 a.C.' },
  { t: 'Coragem não é a ausência de medo, mas a decisão de que algo é mais importante.', a: 'Ambrose Redmoon', y: '1991' },
  { t: 'Não há fracasso, exceto em não tentar mais.', a: 'Elbert Hubbard', y: '1912' },
  { t: 'Cada conquista começa com a decisão de tentar.', a: 'Gail Devers', y: '1996' },
  { t: 'Quando o caminho se torna difícil, os difíceis seguem em frente.', a: 'Joseph P. Kennedy', y: '1957' },
  { t: 'Cair sete vezes; levantar oito.', a: 'Provérbio japonês', y: 'tradicional' },
  { t: 'O bambu não cresce alto sem ter raízes profundas.', a: 'Provérbio chinês', y: 'tradicional' },
  { t: 'A pedra do moinho mói pouco, mas mói sempre.', a: 'Provérbio brasileiro', y: 'tradicional' },
  { t: 'Não tenho talentos especiais. Sou apenas apaixonadamente curioso.', a: 'Albert Einstein', y: '1952' },
  { t: 'A persistência é o caminho do sucesso.', a: 'Charles Chaplin', y: '1940' },
  { t: 'Faça do estudo a sua mais agradável obrigação.', a: 'Provérbio acadêmico', y: 'tradicional' },
  { t: 'Não chegamos a lugar algum sem partir.', a: 'Antoine de Saint-Exupéry', y: '1943' },
  { t: 'Sempre parece impossível até ser feito.', a: 'Nelson Mandela', y: '2001' },
  { t: 'Não há vento favorável para quem não sabe aonde vai.', a: 'Sêneca', y: '60' },
  { t: 'A coragem é a primeira das virtudes humanas.', a: 'Aristóteles', y: '≈340 a.C.' },
  { t: 'A ignorância afirma. A ciência duvida. A sabedoria reflete.', a: 'Aristóteles', y: '≈340 a.C.' },
  { t: 'Estude o passado se você quiser definir o futuro.', a: 'Confúcio', y: '≈500 a.C.' },
  { t: 'O mestre cessou de aprender quando começou a temer aprender.', a: 'Provérbio popular', y: 'tradicional' },
  { t: 'Quem aprende e usa, é mestre. Quem só aprende, é estudante.', a: 'Provérbio acadêmico', y: 'tradicional' },
  { t: 'Os que sabem amar a si mesmos sabem ler.', a: 'Jorge Luis Borges', y: '1969' },
  { t: 'Sempre imaginei o paraíso como uma espécie de biblioteca.', a: 'Jorge Luis Borges', y: '1971' },
  { t: 'A leitura é uma conversação com os homens mais ilustres dos séculos passados.', a: 'René Descartes', y: '1637' },
  { t: 'Nunca subestime o poder de um livro.', a: 'Provérbio popular', y: 'tradicional' },
  { t: 'Ler é como respirar — necessário para a vida da mente.', a: 'Provérbio popular', y: 'tradicional' },
  { t: 'O livro é como um machado para o mar congelado dentro de nós.', a: 'Franz Kafka', y: '1904' },
  { t: 'Não tenha medo de avançar lentamente. Tenha medo de ficar parado.', a: 'Provérbio chinês', y: 'tradicional' },
  { t: 'A jornada de mil milhas começa com um passo.', a: 'Lao Tzu', y: '≈600 a.C.' },
  { t: 'Conhece a ti mesmo, conhece teu inimigo. Mil batalhas, mil vitórias.', a: 'Sun Tzu (A Arte da Guerra)', y: '≈500 a.C.' },
  { t: 'A guerra é vencida antes da batalha.', a: 'Sun Tzu (A Arte da Guerra)', y: '≈500 a.C.' },
  { t: 'O melhor dos guerreiros não tem inimigos.', a: 'Lao Tzu', y: '≈600 a.C.' },
  { t: 'A mente é tudo. Você se torna o que pensa.', a: 'Buda (atribuído)', y: '≈500 a.C.' },
  { t: 'O livro é o melhor amigo do estudante.', a: 'Provérbio acadêmico', y: 'tradicional' },
  { t: 'Os jovens precisam de modelos, não de críticos.', a: 'John Wooden', y: '1973' },
  { t: 'Pequenas coisas feitas com grande amor mudam o mundo.', a: 'Madre Teresa', y: '1979' },
  { t: 'Aprenda como se fosse viver para sempre.', a: 'Mahatma Gandhi', y: '1925' },

  // ===== Mais frases originais — fechamento =====
  'Volte amanhã. O caderno espera.',
  'O exercício 1 do amanhã é o exercício 365 do ano que vem.',
  'O melhor matemático do seu bairro pode ser você. Sente e estude.',
  'O melhor matemático da sua família pode ser você. Estude.',
  'O futuro do seu nome no diploma depende do hoje.',
  'Não tem talento? Tem método. E método vence talento desorganizado.',
  'O mundo precisa de mais gente que sabe pensar com matemática. Seja uma.',
  'Estudar matemática é exercício de cidadania. Cidadão informado é cidadão livre.',
  'Você é o motivo. Estude por você.',
  'Bom dia, estudante. Vamos ao caderno.',
  'Boa noite, estudante. Mais cinco minutos antes de dormir.',
  'Bom domingo, estudante. Uma página, e descansa.',
]

