/**
 * Banco de provas integradas. Cada prova combina vários trimestres
 * com 10-15 questões. Cada questão tem gabarito + explicação passo a passo.
 *
 * REGRA: questões adaptadas (paráfrase, números BR) dos livros do
 * /livros e de provas reais (ENEM, ITA, IME, Olimpíada Brasileira).
 */

export type Dificuldade =
  | 'aplicacao'
  | 'compreensao'
  | 'modelagem'
  | 'desafio'
  | 'demonstracao'

export interface Questao {
  numero: number
  enunciado: string
  alternativas?: string[]
  /** Resposta numérica ou letra. */
  resposta: string
  /** Explicação passo a passo, formato Markdown. */
  passos: string
  dificuldade: Dificuldade
  /** Aulas (slugs) cujos conceitos esta questão cobre. */
  aulasCobertas: string[]
}

export interface Prova {
  id: string
  titulo: string
  descricao: string
  duracaoMinutos: number
  trimestresAlvo: string[]
  /** Curva de dificuldade: 1 (suave) a 5 (vestibular pesado). */
  intensidade: 1 | 2 | 3 | 4 | 5
  /** Estimativa de "ano EM" para qual a prova é apropriada. */
  publicoAlvo: '1.º ano' | '2.º ano' | '3.º ano' | 'Pré-vestibular'
  questoes: Questao[]
}

export const PROVAS: Prova[] = [
  {
    id: 'p01-funcoes-basicas',
    titulo: 'Prova 1 — Funções, afim, quadrática',
    descricao: 'Cobre Trim 1 do Ano 1: funções, domínio, afim, quadrática.',
    duracaoMinutos: 90,
    trimestresAlvo: ['Trim 1'],
    intensidade: 2,
    publicoAlvo: '1.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: 'Determine o domínio máximo de $f(x) = \\sqrt{x - 3}$.',
        resposta: '$[3, +\\infty)$',
        passos:
          '**Passo 1**: para $\\sqrt{u}$ ser real, $u \\geq 0$.\n\n**Passo 2**: $x - 3 \\geq 0 \\Rightarrow x \\geq 3$.\n\n**Resposta**: $[3, +\\infty)$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-02-funcoes'],
      },
      {
        numero: 2,
        enunciado: 'A função afim $f(x) = ax + b$ satisfaz $f(1) = 5$ e $f(3) = 11$. Determine $a$ e $b$.',
        resposta: '$a = 3, b = 2$',
        passos:
          '**Passo 1**: De $f(1) = 5$: $a + b = 5$.\n\n**Passo 2**: De $f(3) = 11$: $3a + b = 11$.\n\n**Passo 3**: Subtraindo: $2a = 6 \\Rightarrow a = 3$. Logo $b = 5 - 3 = 2$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-03-afim'],
      },
      {
        numero: 3,
        enunciado: 'Encontre o vértice da parábola $f(x) = x^2 - 6x + 5$.',
        resposta: '$(3, -4)$',
        passos:
          '**Passo 1**: $x_V = -b/(2a) = 6/2 = 3$.\n\n**Passo 2**: $y_V = f(3) = 9 - 18 + 5 = -4$.\n\n**Resposta**: $(3, -4)$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-04-quadratica'],
      },
      {
        numero: 4,
        enunciado: 'A função custo é $C(q) = 200 + 8q + 0{,}1q^2$. Calcule o custo médio em $q = 50$.',
        resposta: 'R\\$ 16,00 por unidade',
        passos:
          '**Passo 1**: $C(50) = 200 + 400 + 250 = 850$.\n\n**Passo 2**: Custo médio = $C/q = 850/50 = 17$. Confira o cálculo de novo: $0{,}1 \\cdot 2500 = 250$, $8 \\cdot 50 = 400$, $200 + 400 + 250 = 850$, $850/50 = 17$.\n\n**Resposta**: R\\$ 17,00.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-04-quadratica'],
      },
      {
        numero: 5,
        enunciado: 'Resolva: $|2x - 3| < 5$.',
        resposta: '$x \\in (-1, 4)$',
        passos:
          '**Passo 1**: $|2x - 3| < 5 \\iff -5 < 2x - 3 < 5$.\n\n**Passo 2**: Somando 3: $-2 < 2x < 8$.\n\n**Passo 3**: Dividindo por 2: $-1 < x < 4$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-01-conjuntos-intervalos'],
      },
      {
        numero: 6,
        enunciado: 'Determine se a função $f(x) = x^2 + 1$ definida em $\\mathbb{R}$ é injetora.',
        resposta: 'Não é injetora',
        passos:
          '**Passo 1**: Teste com 2 valores distintos: $f(1) = 2$ e $f(-1) = 2$.\n\n**Passo 2**: Como $1 \\neq -1$ mas $f(1) = f(-1)$, a função NÃO é injetora.\n\n**Observação**: ela seria injetora se restringíssemos o domínio a $[0, +\\infty)$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-02-funcoes'],
      },
      {
        numero: 7,
        enunciado: 'Sejam $f(x) = 2x + 1$ e $g(x) = x^2$. Calcule $(f \\circ g)(3)$.',
        resposta: '19',
        passos:
          '**Passo 1**: $g(3) = 9$.\n\n**Passo 2**: $f(g(3)) = f(9) = 2(9) + 1 = 19$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-05-composicao-inversa'],
      },
      {
        numero: 8,
        enunciado: 'Calcule a TVM de $f(x) = x^2$ em $[1, 4]$.',
        resposta: '5',
        passos:
          '**Passo 1**: TVM $= \\frac{f(4) - f(1)}{4 - 1} = \\frac{16 - 1}{3} = \\frac{15}{3} = 5$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-09-taxa-variacao'],
      },
      {
        numero: 9,
        enunciado: 'Resolva $4^x = 32$.',
        resposta: '$x = 5/2$',
        passos:
          '**Passo 1**: Reescreva com mesma base: $4^x = (2^2)^x = 2^{2x}$ e $32 = 2^5$.\n\n**Passo 2**: $2^{2x} = 2^5 \\Rightarrow 2x = 5 \\Rightarrow x = 5/2$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-06-exponencial'],
      },
      {
        numero: 10,
        enunciado: 'Resolva $\\log_2 x + \\log_2 (x - 2) = 3$.',
        resposta: '$x = 4$',
        passos:
          '**Passo 1**: Use $\\log a + \\log b = \\log(ab)$: $\\log_2(x(x-2)) = 3$.\n\n**Passo 2**: $x(x-2) = 2^3 = 8$, ou seja, $x^2 - 2x - 8 = 0$.\n\n**Passo 3**: Bhaskara: $x = (2 \\pm \\sqrt{4 + 32})/2 = (2 \\pm 6)/2$. Soluções: $x = 4$ ou $x = -2$.\n\n**Passo 4**: Como o domínio exige $x > 2$, a única solução válida é $x = 4$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-07-logaritmo'],
      },
    ],
  },
  {
    id: 'p02-trig-completa',
    titulo: 'Prova 2 — Trigonometria completa',
    descricao: 'Cobre Trim 2 do Ano 1: razões trig, círculo, equações, leis.',
    duracaoMinutos: 90,
    trimestresAlvo: ['Trim 2'],
    intensidade: 3,
    publicoAlvo: '1.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: 'Calcule $\\sin(60°) + \\cos(30°)$.',
        resposta: '$\\sqrt{3}$',
        passos: '**Passo 1**: $\\sin(60°) = \\sqrt{3}/2$ e $\\cos(30°) = \\sqrt{3}/2$.\n\n**Passo 2**: Soma = $\\sqrt{3}/2 + \\sqrt{3}/2 = \\sqrt{3}$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-11-trig-triangulo'],
      },
      {
        numero: 2,
        enunciado: 'Converta $135°$ para radianos.',
        resposta: '$3\\pi/4$',
        passos: '**Passo 1**: $1° = \\pi/180$ rad. **Passo 2**: $135 \\cdot \\pi/180 = 3\\pi/4$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-12-circulo-trigonometrico'],
      },
      {
        numero: 3,
        enunciado: 'Resolva $\\sin x = 1/2$ em $[0, 2\\pi)$.',
        resposta: '$x \\in \\{\\pi/6, 5\\pi/6\\}$',
        passos: '**Passo 1**: $\\sin x = 1/2 \\Rightarrow x = \\pi/6$ ou $x = \\pi - \\pi/6 = 5\\pi/6$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-14-equacoes-trigonometricas'],
      },
      {
        numero: 4,
        enunciado: 'Triângulo com $a = 5$, $b = 7$, $C = 60°$. Calcule $c$.',
        resposta: '$c = \\sqrt{39} \\approx 6{,}24$',
        passos: '**Passo 1**: Lei dos cossenos: $c^2 = a^2 + b^2 - 2ab\\cos C$.\n\n**Passo 2**: $c^2 = 25 + 49 - 70 \\cdot 0{,}5 = 74 - 35 = 39$.\n\n**Passo 3**: $c = \\sqrt{39}$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-15-leis-senos-cossenos'],
      },
      {
        numero: 5,
        enunciado: 'A maré em Salvador é $h(t) = 2 + 1{,}5\\sin(\\pi t / 6)$ (m, $t$ em horas). Quando atinge a altura máxima?',
        resposta: '$t = 3$ horas',
        passos: '**Passo 1**: $h$ máxima quando $\\sin(\\pi t/6) = 1$.\n\n**Passo 2**: $\\pi t/6 = \\pi/2 \\Rightarrow t = 3$ h.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-13-funcoes-trigonometricas'],
      },
      {
        numero: 6,
        enunciado: 'Calcule a soma da PA $1, 4, 7, \\ldots, 100$.',
        resposta: '$S = 1717$',
        passos: '**Passo 1**: $a_n = 100$: $100 = 1 + 3(n-1) \\Rightarrow n = 34$.\n\n**Passo 2**: $S_{34} = 34(1 + 100)/2 = 34 \\cdot 50{,}5 = 1717$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-17-pa'],
      },
      {
        numero: 7,
        enunciado: 'Calcule $\\sum_{n=0}^{\\infty} (1/3)^n$.',
        resposta: '$3/2$',
        passos: '**Passo 1**: PG infinita com $a_1 = 1$ e $q = 1/3$.\n\n**Passo 2**: $S = 1/(1 - 1/3) = 1/(2/3) = 3/2$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-18-pg'],
      },
      {
        numero: 8,
        enunciado: 'Calcule $\\lim_{n \\to \\infty} (3n + 5)/(n + 1)$.',
        resposta: '$3$',
        passos: '**Passo 1**: Divida numerador e denominador por $n$: $(3 + 5/n)/(1 + 1/n)$.\n\n**Passo 2**: $5/n \\to 0$ e $1/n \\to 0$, então o limite é $3/1 = 3$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-19-limite-intuitivo'],
      },
      {
        numero: 9,
        enunciado: 'Você está a 50 m da base de uma torre. O ângulo de elevação ao topo é $40°$. Calcule a altura. (Use $\\tan 40° \\approx 0{,}839$.)',
        resposta: 'Aproximadamente $42$ m',
        passos: '**Passo 1**: $\\tan(40°) = \\text{altura}/\\text{distância}$.\n\n**Passo 2**: altura $= 50 \\cdot 0{,}839 \\approx 41{,}95$ m.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-11-trig-triangulo'],
      },
      {
        numero: 10,
        enunciado: 'Resolva $\\cos x = -1/2$ em $[0, 2\\pi)$.',
        resposta: '$x \\in \\{2\\pi/3, 4\\pi/3\\}$',
        passos: '**Passo 1**: $\\cos x = -1/2$ ocorre nos quadrantes II e III.\n\n**Passo 2**: $x = \\pi - \\pi/3 = 2\\pi/3$ ou $x = \\pi + \\pi/3 = 4\\pi/3$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-14-equacoes-trigonometricas'],
      },
    ],
  },
  {
    id: 'p03-geometria-vetores',
    titulo: 'Prova 3 — Geometria analítica e vetores',
    descricao: 'Cobre Trim 3 do Ano 1.',
    duracaoMinutos: 90,
    trimestresAlvo: ['Trim 3'],
    intensidade: 3,
    publicoAlvo: '1.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: 'Distância entre $(2, 5)$ e $(8, 13)$.',
        resposta: '$10$',
        passos: '$d = \\sqrt{(8-2)^2 + (13-5)^2} = \\sqrt{36 + 64} = \\sqrt{100} = 10$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-21-plano-cartesiano'],
      },
      {
        numero: 2,
        enunciado: 'Equação da reta passando por $(0, 4)$ e $(2, 0)$.',
        resposta: '$y = -2x + 4$',
        passos: '**Passo 1**: Inclinação $m = (0 - 4)/(2 - 0) = -2$.\n\n**Passo 2**: Intercepto $y$ é 4 (do ponto $(0, 4)$).\n\n**Passo 3**: $y = -2x + 4$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-22-equacao-reta'],
      },
      {
        numero: 3,
        enunciado: 'Equação da circunferência de centro $(2, -1)$ e raio 5.',
        resposta: '$(x - 2)^2 + (y + 1)^2 = 25$',
        passos: 'Forma reduzida: $(x - h)^2 + (y - k)^2 = r^2$ com $(h, k) = (2, -1)$ e $r = 5$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-24-circunferencia'],
      },
      {
        numero: 4,
        enunciado: 'Calcule $(3, 4) \\cdot (1, 2)$ e o ângulo entre os vetores.',
        resposta: 'Produto = 11; ângulo $\\approx 10{,}3°$',
        passos: '**Passo 1**: Produto escalar $= 3 \\cdot 1 + 4 \\cdot 2 = 11$.\n\n**Passo 2**: $|u| = 5$, $|v| = \\sqrt{5}$.\n\n**Passo 3**: $\\cos\\theta = 11/(5\\sqrt{5}) \\approx 0{,}9839 \\Rightarrow \\theta \\approx 10{,}3°$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-27-produto-escalar'],
      },
      {
        numero: 5,
        enunciado: 'Resolva o sistema $\\begin{cases} 2x + y = 7 \\\\ x - 3y = -2 \\end{cases}$.',
        resposta: '$x = 19/7, y = 11/7$',
        passos: '**Passo 1**: Da primeira equação: $y = 7 - 2x$.\n\n**Passo 2**: Substitui na segunda: $x - 3(7 - 2x) = -2 \\Rightarrow 7x - 21 = -2 \\Rightarrow 7x = 19 \\Rightarrow x = 19/7$.\n\n**Passo 3**: $y = 7 - 38/7 = 11/7$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-29-sistemas-lineares'],
      },
      {
        numero: 6,
        enunciado: 'Massa de 10 kg em rampa $30°$, sem atrito. Aceleração de descida? (Use $g = 10$ m/s².)',
        resposta: '$5$ m/s²',
        passos: 'Componente da gravidade paralela à rampa: $g \\sin 30° = 10 \\cdot 0{,}5 = 5$ m/s².',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-28-aplicacoes-vetores-fisica'],
      },
      {
        numero: 7,
        enunciado: 'Identifique a cônica $x^2/16 + y^2/9 = 1$ e calcule a excentricidade.',
        resposta: 'Elipse, $e = \\sqrt{7}/4 \\approx 0{,}66$',
        passos: '**Passo 1**: Forma de elipse $x^2/a^2 + y^2/b^2 = 1$ com $a^2 = 16, b^2 = 9$, então $a = 4, b = 3$.\n\n**Passo 2**: $c = \\sqrt{a^2 - b^2} = \\sqrt{7}$. Excentricidade $e = c/a = \\sqrt{7}/4 \\approx 0{,}66$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-25-conicas'],
      },
      {
        numero: 8,
        enunciado: 'Avião 700 km/h rumo NE, vento 100 km/h leste. Velocidade resultante (módulo).',
        resposta: 'Aprox. $786$ km/h',
        passos: '**Passo 1**: Componentes do avião: $(700/\\sqrt{2}, 700/\\sqrt{2}) \\approx (495, 495)$ km/h.\n\n**Passo 2**: Vento: $(100, 0)$.\n\n**Passo 3**: Soma: $(595, 495)$. Módulo: $\\sqrt{595^2 + 495^2} = \\sqrt{354025 + 245025} = \\sqrt{599050} \\approx 774$ km/h.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-28-aplicacoes-vetores-fisica'],
      },
      {
        numero: 9,
        enunciado: 'Vetor unitário na direção de $(6, 8)$.',
        resposta: '$(0{,}6,\\ 0{,}8)$',
        passos: '$|(6,8)| = 10$. Versor $= (6/10, 8/10) = (0{,}6, 0{,}8)$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-26-vetores-plano'],
      },
      {
        numero: 10,
        enunciado: 'Coeficiente angular da reta perpendicular a $y = 2x - 3$ passando por $(4, 1)$.',
        resposta: '$y = -x/2 + 3$',
        passos: '**Passo 1**: Perpendicular tem $m_2 \\cdot m_1 = -1 \\Rightarrow m_2 = -1/2$.\n\n**Passo 2**: $y - 1 = -1/2(x - 4) \\Rightarrow y = -x/2 + 2 + 1 = -x/2 + 3$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-23-posicao-relativa-retas'],
      },
    ],
  },
  {
    id: 'p04-anual-ano-1',
    titulo: 'Prova 4 — Anual integradora (Ano 1)',
    descricao: 'Workshop integrador final do Ano 1: 15 questões.',
    duracaoMinutos: 180,
    trimestresAlvo: ['Trims 1-4'],
    intensidade: 3,
    publicoAlvo: '1.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: 'Domínio de $f(x) = \\log_2(x^2 - 9)$.',
        resposta: '$(-\\infty, -3) \\cup (3, +\\infty)$',
        passos: '**Passo 1**: Argumento do log $> 0$: $x^2 - 9 > 0$.\n\n**Passo 2**: $x^2 > 9 \\Rightarrow |x| > 3 \\Rightarrow x < -3$ ou $x > 3$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-07-logaritmo', 'aula-04-quadratica'],
      },
      {
        numero: 2,
        enunciado: 'Determine $a$ tal que $f(x) = (a-1)x^2 + 3x - 2$ tenha vértice em $x = 1$.',
        resposta: '$a = -1/2$',
        passos: '**Passo 1**: $x_V = -b/(2a) = -3/(2(a-1)) = 1$.\n\n**Passo 2**: $-3 = 2(a-1) \\Rightarrow a - 1 = -3/2 \\Rightarrow a = -1/2$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-04-quadratica'],
      },
      {
        numero: 3,
        enunciado: 'Quanto tempo R\\$ 1.000 dobra a 6\\% a.a. composto continuamente? (Use $\\ln 2 = 0{,}693$.)',
        resposta: '$\\approx 11{,}55$ anos',
        passos: '**Passo 1**: $S = S_0 e^{rt}$. $2S_0 = S_0 e^{0{,}06 t}$.\n\n**Passo 2**: $\\ln 2 = 0{,}06 t \\Rightarrow t = 0{,}693/0{,}06 = 11{,}55$ anos.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-08-crescimento'],
      },
      {
        numero: 4,
        enunciado: 'Bola lançada vertical com $v_0 = 30$ m/s. Altura $h(t) = 30t - 5t^2$. Altura máxima?',
        resposta: '$45$ m',
        passos: '**Passo 1**: Vértice: $t = -30/(2 \\cdot -5) = 3$ s.\n\n**Passo 2**: $h(3) = 90 - 45 = 45$ m.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-04-quadratica'],
      },
      {
        numero: 5,
        enunciado: 'Anagramas de "MATEMATICA" (10 letras: 3A, 2M, 2T, 1E, 1I, 1C).',
        resposta: '$10!/(3!2!2!) = 151{,}200$',
        passos: '**Passo 1**: Permutação com repetição: $n!/(n_1! n_2! \\ldots)$.\n\n**Passo 2**: $10! = 3.628.800$. Denominador: $6 \\cdot 2 \\cdot 2 = 24$. Resultado: $151.200$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-37-permutacoes-arranjos'],
      },
      {
        numero: 6,
        enunciado: 'Mega-Sena: $P(\\text{acertar 6})$.',
        resposta: '$1/\\binom{60}{6} = 1/50.063.860$',
        passos: '$\\binom{60}{6} = 60!/(6! \\cdot 54!) = 50.063.860$. Probabilidade = $1$ em $\\sim 50$ milhões.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-38-combinacoes', 'aula-39-probabilidade'],
      },
      {
        numero: 7,
        enunciado: 'Calcule $\\det \\begin{pmatrix} 2 & 3 \\\\ 1 & 4 \\end{pmatrix}$.',
        resposta: '$5$',
        passos: '$\\det = ad - bc = 2 \\cdot 4 - 3 \\cdot 1 = 8 - 3 = 5$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-34-determinantes'],
      },
      {
        numero: 8,
        enunciado: 'Calcule a inversa de $A = \\begin{pmatrix} 1 & 2 \\\\ 3 & 5 \\end{pmatrix}$.',
        resposta: '$A^{-1} = \\begin{pmatrix} -5 & 2 \\\\ 3 & -1 \\end{pmatrix}$',
        passos: '**Passo 1**: $\\det A = 5 - 6 = -1$.\n\n**Passo 2**: $A^{-1} = \\frac{1}{-1}\\begin{pmatrix} 5 & -2 \\\\ -3 & 1 \\end{pmatrix} = \\begin{pmatrix} -5 & 2 \\\\ 3 & -1 \\end{pmatrix}$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-33-transposta-inversa'],
      },
      {
        numero: 9,
        enunciado: 'Doença com $P(D) = 0{,}001$. Teste: sensibilidade 99%, especificidade 95%. $P(D | +)$.',
        resposta: '$\\approx 1{,}94\\%$',
        passos: '**Bayes**: $P(D|+) = P(+|D) \\cdot P(D)/P(+)$.\n\n**Passo 1**: $P(+|D) = 0{,}99$, $P(+|D^c) = 1 - 0{,}95 = 0{,}05$.\n\n**Passo 2**: $P(+) = 0{,}99 \\cdot 0{,}001 + 0{,}05 \\cdot 0{,}999 = 0{,}00099 + 0{,}049995 \\approx 0{,}051$.\n\n**Passo 3**: $P(D|+) = 0{,}00099/0{,}051 \\approx 0{,}0194 = 1{,}94\\%$. Apenas 1,94% mesmo com teste 99%! Base rate fallacy.',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-39-probabilidade'],
      },
      {
        numero: 10,
        enunciado: 'TVM de $f(x) = x^2 + 3x$ em $[1, 5]$.',
        resposta: '$9$',
        passos: 'TVM $= (f(5) - f(1))/(5 - 1) = (25 + 15 - 1 - 3)/4 = 36/4 = 9$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-09-taxa-variacao'],
      },
      {
        numero: 11,
        enunciado: 'Triângulo $a = 4$, $b = 5$, $c = 6$. Calcule área via Heron.',
        resposta: '$\\approx 9{,}92$',
        passos: '**Passo 1**: $s = (4+5+6)/2 = 7{,}5$.\n\n**Passo 2**: Área $= \\sqrt{7{,}5 \\cdot 3{,}5 \\cdot 2{,}5 \\cdot 1{,}5} = \\sqrt{98{,}4375} \\approx 9{,}92$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-15-leis-senos-cossenos'],
      },
      {
        numero: 12,
        enunciado: 'Esboce $y = -2(x - 3)^2 + 4$ identificando vértice e concavidade.',
        resposta: 'Vértice $(3, 4)$, concavidade para baixo, raízes $x = 3 \\pm \\sqrt{2}$',
        passos: 'Forma canônica $a(x - h)^2 + k$: vértice $(3, 4)$. Como $a = -2 < 0$, abre para baixo. Raízes: $-2(x-3)^2 + 4 = 0 \\Rightarrow (x-3)^2 = 2 \\Rightarrow x = 3 \\pm \\sqrt{2}$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-04-quadratica'],
      },
      {
        numero: 13,
        enunciado: 'Resolva $\\sin(2x) = 1$ em $[0, 2\\pi)$.',
        resposta: '$x = \\pi/4$ ou $x = 5\\pi/4$',
        passos: '**Passo 1**: $\\sin(2x) = 1 \\Rightarrow 2x = \\pi/2 + 2k\\pi$.\n\n**Passo 2**: $x = \\pi/4 + k\\pi$. Em $[0, 2\\pi)$: $k = 0 \\Rightarrow \\pi/4$; $k = 1 \\Rightarrow 5\\pi/4$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-14-equacoes-trigonometricas'],
      },
      {
        numero: 14,
        enunciado: 'Aplicação financeira: R\\$ 5.000 a 0,8% a.m. composto. Saldo em 24 meses.',
        resposta: '$\\approx$ R\\$ 6.052,49',
        passos: '$S = 5000 \\cdot (1{,}008)^{24}$. $(1{,}008)^{24} \\approx 1{,}21049$. Saldo $\\approx 6052{,}45$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-08-crescimento'],
      },
      {
        numero: 15,
        enunciado: 'Demonstre que $\\sqrt{2}$ é irracional.',
        resposta: 'Demonstração por absurdo (ver passos).',
        passos: '**Passo 1**: Suponha $\\sqrt{2} = p/q$ com $p, q \\in \\mathbb{Z}$, $\\gcd(p, q) = 1$.\n\n**Passo 2**: Então $p^2 = 2q^2$. Logo $p^2$ é par, então $p$ é par. Escreva $p = 2k$.\n\n**Passo 3**: $4k^2 = 2q^2 \\Rightarrow q^2 = 2k^2$. Logo $q$ é par.\n\n**Passo 4**: Mas se $p$ e $q$ são ambos pares, $\\gcd(p, q) \\geq 2$, contradição. ∎',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-01-conjuntos-intervalos'],
      },
    ],
  },
  {
    id: 'p05-limites',
    titulo: 'Prova 5 — Limites e continuidade',
    descricao: 'Cobre Trim 5 do Ano 2.',
    duracaoMinutos: 90,
    trimestresAlvo: ['Trim 5'],
    intensidade: 3,
    publicoAlvo: '2.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: 'Calcule $\\lim_{x \\to 2} (3x^2 - x + 1)$.',
        resposta: '$11$',
        passos: 'Substitui direto: $3(4) - 2 + 1 = 12 - 1 = 11$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-42-propriedades-limites'],
      },
      {
        numero: 2,
        enunciado: '$\\lim_{x \\to 2} (x^2 - 4)/(x - 2)$.',
        resposta: '$4$',
        passos: 'Fatoração: $(x-2)(x+2)/(x-2) = x + 2 \\to 4$ quando $x \\to 2$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-42-propriedades-limites'],
      },
      {
        numero: 3,
        enunciado: '$\\lim_{x \\to 0} \\sin(5x)/x$.',
        resposta: '$5$',
        passos: 'Use $\\lim \\sin(kx)/x = k$. Aqui $k = 5$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-45-limites-fundamentais'],
      },
      {
        numero: 4,
        enunciado: '$\\lim_{x \\to \\infty} (3x^2 - 5)/(x^2 + 2)$.',
        resposta: '$3$',
        passos: 'Razão de polinômios de mesmo grau: razão dos coeficientes líderes = $3/1 = 3$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-44-limites-laterais'],
      },
      {
        numero: 5,
        enunciado: '$\\lim_{x \\to 0^+} 1/x$.',
        resposta: '$+\\infty$',
        passos: 'Pela direita ($x > 0$ pequeno), $1/x$ cresce sem cota.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-44-limites-laterais'],
      },
      {
        numero: 6,
        enunciado: '$\\lim_{x \\to \\infty} (1 + 2/x)^x$.',
        resposta: '$e^2$',
        passos: 'Use $\\lim (1 + a/x)^x = e^a$. Aqui $a = 2$, então $e^2$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-45-limites-fundamentais'],
      },
      {
        numero: 7,
        enunciado: 'Mostre que $f(x) = (x^2 - 9)/(x - 3)$ tem descontinuidade removível em $x = 3$. Conserte.',
        resposta: 'Defina $f(3) = 6$',
        passos: '**Passo 1**: $\\lim_{x \\to 3} f(x) = \\lim (x+3) = 6$.\n\n**Passo 2**: Defina $\\tilde f(3) = 6$, $\\tilde f(x) = f(x)$ caso contrário, e $\\tilde f$ é contínua.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-43-continuidade'],
      },
      {
        numero: 8,
        enunciado: 'Mostre via TVI que $x^3 - 2x - 5 = 0$ tem raiz em $(2, 3)$.',
        resposta: 'Sim, por TVI',
        passos: '**Passo 1**: $f(2) = 8 - 4 - 5 = -1 < 0$.\n\n**Passo 2**: $f(3) = 27 - 6 - 5 = 16 > 0$.\n\n**Passo 3**: $f$ é contínua e muda de sinal $\\Rightarrow$ raiz em $(2, 3)$ por TVI.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-46-tvi-tvm'],
      },
      {
        numero: 9,
        enunciado: 'Determine assíntotas de $f(x) = (2x^2 + 3)/(x^2 - 1)$.',
        resposta: 'AH: $y = 2$. AVs: $x = 1$ e $x = -1$.',
        passos: '**AH**: $\\lim_{x \\to \\pm\\infty} f(x) = 2$ (razão de coef. líderes).\n\n**AVs**: denominador zera em $x = \\pm 1$ e numerador não, então $f \\to \\pm\\infty$ nesses pontos.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-47-assintotas'],
      },
      {
        numero: 10,
        enunciado: '$\\lim_{n \\to \\infty} n!/n^n$.',
        resposta: '$0$',
        passos: '**Passo 1**: $n!/n^n = (1/n)(2/n)(3/n)\\cdots(n/n)$.\n\n**Passo 2**: Cada fator $\\leq 1$, e o primeiro $1/n \\to 0$. Pelo confronto, limite é 0.',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-49-limite-sequencias'],
      },
    ],
  },
  {
    id: 'p06-derivadas',
    titulo: 'Prova 6 — Derivadas e regras',
    descricao: 'Cobre Trim 6 do Ano 2.',
    duracaoMinutos: 90,
    trimestresAlvo: ['Trim 6'],
    intensidade: 3,
    publicoAlvo: '2.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: 'Derive $f(x) = 3x^4 - 2x^3 + x - 5$.',
        resposta: '$f\'(x) = 12x^3 - 6x^2 + 1$',
        passos: 'Regra da potência termo a termo: $(3x^4)\' = 12x^3$, $(-2x^3)\' = -6x^2$, $(x)\' = 1$, $(-5)\' = 0$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-52-regras-derivacao'],
      },
      {
        numero: 2,
        enunciado: 'Derive $f(x) = (x^2 + 1)\\sin x$.',
        resposta: '$f\'(x) = 2x \\sin x + (x^2 + 1)\\cos x$',
        passos: 'Regra do produto: $(uv)\' = u\'v + uv\'$ com $u = x^2 + 1$, $v = \\sin x$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-52-regras-derivacao'],
      },
      {
        numero: 3,
        enunciado: 'Derive $f(x) = \\sin(3x^2 + 1)$.',
        resposta: '$f\'(x) = 6x \\cos(3x^2 + 1)$',
        passos: 'Regra da cadeia: $(\\sin g)\' = \\cos g \\cdot g\'$. Aqui $g = 3x^2 + 1$, $g\' = 6x$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-53-regra-cadeia'],
      },
      {
        numero: 4,
        enunciado: 'Reta tangente a $y = x^3$ em $x = 2$.',
        resposta: '$y = 12x - 16$',
        passos: '**Passo 1**: $f\'(x) = 3x^2$, $f\'(2) = 12$.\n\n**Passo 2**: $f(2) = 8$.\n\n**Passo 3**: $y - 8 = 12(x - 2) \\Rightarrow y = 12x - 16$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-51-derivada-definicao'],
      },
      {
        numero: 5,
        enunciado: 'Derive implicitamente $x^2 + y^2 = 25$ e calcule $y\'$ em $(3, 4)$.',
        resposta: '$y\' = -3/4$',
        passos: '**Passo 1**: $2x + 2yy\' = 0 \\Rightarrow y\' = -x/y$.\n\n**Passo 2**: Em $(3, 4)$: $y\' = -3/4$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-54-derivadas-implicitas'],
      },
      {
        numero: 6,
        enunciado: 'Derive $f(x) = e^{x^2}$.',
        resposta: '$f\'(x) = 2x e^{x^2}$',
        passos: 'Cadeia: $(e^g)\' = e^g \\cdot g\'$. $g = x^2$, $g\' = 2x$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-53-regra-cadeia'],
      },
      {
        numero: 7,
        enunciado: 'Derive $f(x) = \\ln(x^2 + 1)$.',
        resposta: '$f\'(x) = 2x/(x^2 + 1)$',
        passos: 'Cadeia: $(\\ln g)\' = g\'/g$ com $g = x^2 + 1$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-53-regra-cadeia'],
      },
      {
        numero: 8,
        enunciado: 'Calcule $f\'\'(x)$ para $f(x) = x^4 - 6x^2$.',
        resposta: '$f\'\'(x) = 12x^2 - 12$',
        passos: '$f\' = 4x^3 - 12x$; $f\'\' = 12x^2 - 12$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-55-derivadas-superiores'],
      },
      {
        numero: 9,
        enunciado: 'Posição $s(t) = t^3 - 6t^2 + 9t$. Tempo de aceleração nula.',
        resposta: '$t = 2$ s',
        passos: '$v = s\' = 3t^2 - 12t + 9$; $a = v\' = 6t - 12$. $a = 0 \\Rightarrow t = 2$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-55-derivadas-superiores'],
      },
      {
        numero: 10,
        enunciado: 'Aproximação linear de $f(x) = \\sqrt{x}$ perto de $a = 4$. Estime $\\sqrt{4{,}1}$.',
        resposta: '$\\approx 2{,}025$',
        passos: '$f\'(x) = 1/(2\\sqrt{x})$, $f\'(4) = 1/4$. Linear: $L(x) = 2 + (x-4)/4$. $L(4{,}1) = 2 + 0{,}025 = 2{,}025$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-57-aproximacao-linear'],
      },
    ],
  },
  {
    id: 'p07-aplicacoes-derivada',
    titulo: 'Prova 7 — Aplicações da derivada',
    descricao: 'Otimização, esboço, L\'Hôpital, Taylor.',
    duracaoMinutos: 90,
    trimestresAlvo: ['Trim 7'],
    intensidade: 4,
    publicoAlvo: '2.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: 'Encontre máximo e mínimo locais de $f(x) = x^3 - 3x^2 - 9x + 5$.',
        resposta: 'Máx local em $x = -1$ ($f = 10$), mín local em $x = 3$ ($f = -22$)',
        passos: '$f\' = 3x^2 - 6x - 9 = 3(x-3)(x+1)$. Pontos críticos: $x = -1, 3$. $f\'\'(x) = 6x - 6$. $f\'\'(-1) = -12 < 0$ (máx); $f\'\'(3) = 12 > 0$ (mín).',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-61-maximos-minimos'],
      },
      {
        numero: 2,
        enunciado: 'Cerca para galinheiro retangular contra parede com 200 m de cerca (3 lados). Maximize a área.',
        resposta: '$x = 50$, $y = 100$, área = $5.000$ m²',
        passos: '$2x + y = 200 \\Rightarrow y = 200 - 2x$. Área $A(x) = x(200-2x) = 200x - 2x^2$. $A\'(x) = 200 - 4x = 0 \\Rightarrow x = 50$. $y = 100$. Área = $5.000$ m².',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-62-otimizacao'],
      },
      {
        numero: 3,
        enunciado: '$\\lim_{x \\to 0} \\sin(x)/x$ via L\'Hôpital.',
        resposta: '$1$',
        passos: 'Forma $0/0$. L\'Hôpital: $\\lim \\cos(x)/1 = 1$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-64-l-hopital'],
      },
      {
        numero: 4,
        enunciado: 'Polinômio de Taylor de grau 2 de $\\cos x$ em $a = 0$.',
        resposta: '$T_2(x) = 1 - x^2/2$',
        passos: '$\\cos(0) = 1$, $\\cos\'(0) = 0$, $\\cos\'\'(0) = -1$. $T_2(x) = 1 + 0 \\cdot x + (-1)x^2/2 = 1 - x^2/2$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-65-taylor'],
      },
      {
        numero: 5,
        enunciado: 'Esboço: pontos de inflexão de $f(x) = x^3 - 6x^2 + 9x$.',
        resposta: '$x = 2$',
        passos: '$f\'\' = 6x - 12 = 0 \\Rightarrow x = 2$. Mudança de sinal de $f\'\'$ confirma inflexão.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-66-concavidade'],
      },
      {
        numero: 6,
        enunciado: 'Newton-Raphson para $f(x) = x^2 - 2$ a partir de $x_0 = 1$. Calcule $x_2$.',
        resposta: '$x_2 \\approx 1{,}4167$',
        passos: '$x_{n+1} = x_n - (x_n^2 - 2)/(2x_n) = (x_n + 2/x_n)/2$. $x_1 = (1 + 2)/2 = 1{,}5$. $x_2 = (1{,}5 + 2/1{,}5)/2 = (1{,}5 + 1{,}333)/2 = 1{,}4167$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-69-newton-raphson'],
      },
      {
        numero: 7,
        enunciado: 'Custo $C(q) = q^2 + 30q + 200$. $q$ que minimiza custo médio $CM = C/q$.',
        resposta: '$q = \\sqrt{200} \\approx 14{,}14$',
        passos: '$CM(q) = q + 30 + 200/q$. $CM\'(q) = 1 - 200/q^2 = 0 \\Rightarrow q^2 = 200$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-67-economia-derivadas'],
      },
      {
        numero: 8,
        enunciado: 'Velocidade média de carro: $s(t) = 5t^2$ m. Velocidade instantânea em $t = 3$.',
        resposta: '$30$ m/s',
        passos: '$v(t) = s\'(t) = 10t$. $v(3) = 30$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-68-cinematica'],
      },
      {
        numero: 9,
        enunciado: '$\\lim_{x \\to 0} (e^x - 1 - x)/x^2$.',
        resposta: '$1/2$',
        passos: 'Forma $0/0$. L\'Hôpital duas vezes: $\\lim (e^x - 1)/(2x) \\to e^x/2 \\to 1/2$.',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-64-l-hopital'],
      },
      {
        numero: 10,
        enunciado: 'Caixa sem tampa de cartolina 30×30, dobrando $x$ nos cantos. $x$ que maximiza volume.',
        resposta: '$x = 5$, V = $2.000$ cm³',
        passos: '$V = x(30-2x)^2$. $V\' = (30-2x)^2 + x \\cdot 2(30-2x)(-2) = (30-2x)(30-2x - 4x) = (30-2x)(30-6x)$. $V\' = 0 \\Rightarrow x = 15$ (degenerado) ou $x = 5$. Vmax em $x = 5$: $V = 5 \\cdot 400 = 2.000$.',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-62-otimizacao'],
      },
    ],
  },
  {
    id: 'p08-integral',
    titulo: 'Prova 8 — Cálculo Integral',
    descricao: 'Cobre Trim 9 do Ano 3.',
    duracaoMinutos: 90,
    trimestresAlvo: ['Trim 9'],
    intensidade: 3,
    publicoAlvo: '3.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: '$\\int (3x^2 + 2x - 1) dx$.',
        resposta: '$x^3 + x^2 - x + C$',
        passos: 'Termo a termo: $\\int 3x^2 = x^3$, $\\int 2x = x^2$, $\\int -1 = -x$. Soma + C.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-81-antiderivada'],
      },
      {
        numero: 2,
        enunciado: '$\\int_0^1 (x^2 + 1) dx$.',
        resposta: '$4/3$',
        passos: '$F(x) = x^3/3 + x$. $F(1) - F(0) = (1/3 + 1) - 0 = 4/3$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-82-integral-definida'],
      },
      {
        numero: 3,
        enunciado: '$\\int 2x \\cos(x^2) dx$ (substituição).',
        resposta: '$\\sin(x^2) + C$',
        passos: 'Substitua $u = x^2$, $du = 2x dx$. $\\int \\cos(u) du = \\sin u + C$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-84-substituicao'],
      },
      {
        numero: 4,
        enunciado: '$\\int x e^x dx$ (por partes).',
        resposta: '$xe^x - e^x + C$',
        passos: '$u = x, dv = e^x dx \\Rightarrow du = dx, v = e^x$. $\\int u dv = uv - \\int v du = xe^x - e^x + C$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-85-por-partes'],
      },
      {
        numero: 5,
        enunciado: 'Área entre $y = x^2$ e $y = x$ em $[0, 1]$.',
        resposta: '$1/6$',
        passos: '$\\int_0^1 (x - x^2) dx = [x^2/2 - x^3/3]_0^1 = 1/2 - 1/3 = 1/6$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-88-area-curvas'],
      },
      {
        numero: 6,
        enunciado: 'Volume do sólido obtido girando $y = \\sqrt{x}$ em $[0, 4]$ em torno do eixo $x$.',
        resposta: '$8\\pi$',
        passos: '$V = \\pi \\int_0^4 (\\sqrt{x})^2 dx = \\pi \\int_0^4 x dx = \\pi [x^2/2]_0^4 = 8\\pi$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-89-volume'],
      },
      {
        numero: 7,
        enunciado: '$\\int 1/(x^2 + 1) dx$.',
        resposta: '$\\arctan x + C$',
        passos: 'Identidade direta: $(d/dx)\\arctan x = 1/(x^2+1)$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-87-integrais-trig'],
      },
      {
        numero: 8,
        enunciado: 'TFC: calcule $(d/dx) \\int_0^x \\sin(t^2) dt$.',
        resposta: '$\\sin(x^2)$',
        passos: 'TFC1: derivada da integral é o integrando.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-83-tfc'],
      },
      {
        numero: 9,
        enunciado: '$\\int 1/(x^2 - 1) dx$ (frações parciais).',
        resposta: '$(1/2)\\ln|(x-1)/(x+1)| + C$',
        passos: '$1/(x^2 - 1) = (1/2)[1/(x-1) - 1/(x+1)]$. Integrando: $(1/2)[\\ln|x-1| - \\ln|x+1|] = (1/2)\\ln|(x-1)/(x+1)| + C$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-86-fracoes-parciais'],
      },
      {
        numero: 10,
        enunciado: 'Trabalho de força $F(x) = 3x^2$ N de $x = 0$ a $x = 4$ m.',
        resposta: '$64$ J',
        passos: '$W = \\int_0^4 3x^2 dx = [x^3]_0^4 = 64$ J.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-82-integral-definida'],
      },
    ],
  },
  {
    id: 'p09-edo-aplicada',
    titulo: 'Prova 9 — EDOs aplicadas',
    descricao: 'Cobre Trim 10: separável, linear, vibrações, RLC, Euler.',
    duracaoMinutos: 90,
    trimestresAlvo: ['Trim 10'],
    intensidade: 4,
    publicoAlvo: '3.º ano',
    questoes: [
      {
        numero: 1,
        enunciado: 'Resolva $dy/dx = 2xy$ com $y(0) = 3$.',
        resposta: '$y(x) = 3 e^{x^2}$',
        passos: 'Separável: $dy/y = 2x dx$. Integra: $\\ln|y| = x^2 + C$. $y = A e^{x^2}$. Com $y(0) = 3$: $A = 3$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-92-edo-separavel'],
      },
      {
        numero: 2,
        enunciado: 'Café a 90°C em sala 25°C esfria com $k = 0{,}1$/min. Tempo para 30°C.',
        resposta: '$\\approx 25{,}6$ min',
        passos: 'Newton: $T(t) = 25 + 65 e^{-0{,}1 t}$. $30 = 25 + 65 e^{-0{,}1 t} \\Rightarrow e^{-0{,}1 t} = 5/65 \\Rightarrow t = -\\ln(1/13)/0{,}1 = 25{,}65$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-99-newton-resfriamento'],
      },
      {
        numero: 3,
        enunciado: 'Tempo de duplicação se $\\dot N = 0{,}05 N$.',
        resposta: '$\\approx 13{,}86$ ano',
        passos: '$T = \\ln 2/k = 0{,}693/0{,}05 = 13{,}86$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-94-edo-populacional'],
      },
      {
        numero: 4,
        enunciado: 'EDO característica de $y\'\' + 5y\' + 6y = 0$.',
        resposta: '$y = c_1 e^{-2x} + c_2 e^{-3x}$',
        passos: '$\\lambda^2 + 5\\lambda + 6 = 0 \\Rightarrow \\lambda = -2$ ou $\\lambda = -3$. Solução geral é combinação linear.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-95-edo-2-ordem'],
      },
      {
        numero: 5,
        enunciado: 'Frequência natural de massa-mola $m = 2$ kg, $k = 50$ N/m.',
        resposta: '$\\omega = 5$ rad/s',
        passos: '$\\omega = \\sqrt{k/m} = \\sqrt{25} = 5$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-96-vibracoes'],
      },
      {
        numero: 6,
        enunciado: 'Capacitor descarga $V_0 = 10$V em RC = 1s. $V$ em $t = 2$s.',
        resposta: '$V \\approx 1{,}35$V',
        passos: '$V(t) = 10 e^{-t/1} = 10 e^{-2} \\approx 1{,}353$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-97-rlc'],
      },
      {
        numero: 7,
        enunciado: 'Método de Euler para $y\' = y$, $y(0) = 1$, $h = 0{,}1$. Calcule $y_3$.',
        resposta: '$y_3 = 1{,}331$',
        passos: '$y_{n+1} = y_n + h y_n = y_n (1{,}1)$. $y_1 = 1{,}1$, $y_2 = 1{,}21$, $y_3 = 1{,}331$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-98-euler-numerico'],
      },
      {
        numero: 8,
        enunciado: 'Modelo logístico $\\dot N = 0{,}1 N(1 - N/100)$. Capacidade $K$?',
        resposta: '$K = 100$',
        passos: 'Da forma $\\dot N = rN(1 - N/K)$, identificamos $K = 100$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-94-edo-populacional'],
      },
      {
        numero: 9,
        enunciado: 'Carbono-14 ($\\tau_{1/2} = 5730$ anos): osso com $1/8$ do C-14 inicial. Idade?',
        resposta: '$3 \\cdot 5730 = 17.190$ anos',
        passos: '$1/8 = (1/2)^3$, então 3 meias-vidas = $3 \\cdot 5730 = 17.190$ anos.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-94-edo-populacional'],
      },
      {
        numero: 10,
        enunciado: 'Drogagem: meia-vida 4h, dose 100mg. Quanto resta após 12h?',
        resposta: '$12{,}5$ mg',
        passos: '12h = 3 meias-vidas. Resta $100/(2^3) = 100/8 = 12{,}5$ mg.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-94-edo-populacional'],
      },
    ],
  },
  {
    id: 'p10-final-3-anos',
    titulo: 'Prova 10 — Final integradora (3 anos)',
    descricao: 'Workshop final do programa: 15 questões cobrindo todos os anos.',
    duracaoMinutos: 240,
    trimestresAlvo: ['Anos 1-3'],
    intensidade: 5,
    publicoAlvo: 'Pré-vestibular',
    questoes: [
      {
        numero: 1,
        enunciado: '$\\lim_{x \\to 0} (\\sin 3x)/(\\tan 5x)$.',
        resposta: '$3/5$',
        passos: 'L\'Hôpital ou aproximação: $\\sin 3x \\approx 3x$, $\\tan 5x \\approx 5x$. Razão: $3/5$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-45-limites-fundamentais'],
      },
      {
        numero: 2,
        enunciado: 'Derive $f(x) = \\ln(\\sin x)$.',
        resposta: '$f\'(x) = \\cot x$',
        passos: 'Cadeia: $f\' = (\\cos x)/(\\sin x) = \\cot x$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-53-regra-cadeia'],
      },
      {
        numero: 3,
        enunciado: '$\\int_0^{\\pi/2} \\sin x \\cos x dx$.',
        resposta: '$1/2$',
        passos: 'Substitua $u = \\sin x$. $\\int_0^1 u du = 1/2$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-84-substituicao'],
      },
      {
        numero: 4,
        enunciado: 'EDO $y\' = 3y$, $y(0) = 2$. Solução em $t = 1$.',
        resposta: '$y(1) = 2 e^3 \\approx 40{,}17$',
        passos: '$y(t) = 2 e^{3t}$. $y(1) = 2 e^3 \\approx 40{,}17$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-92-edo-separavel'],
      },
      {
        numero: 5,
        enunciado: 'Determine autovalores de $A = \\begin{pmatrix} 4 & 2 \\\\ 1 & 3 \\end{pmatrix}$.',
        resposta: '$\\lambda_1 = 5, \\lambda_2 = 2$',
        passos: '$\\det(A - \\lambda I) = (4-\\lambda)(3-\\lambda) - 2 = \\lambda^2 - 7\\lambda + 10 = 0$. Bhaskara: $\\lambda = 5$ ou $\\lambda = 2$.',
        dificuldade: 'aplicacao',
        aulasCobertas: ['aula-114-autovalores'],
      },
      {
        numero: 6,
        enunciado: '$X \\sim \\text{Bin}(10, 0{,}3)$. $P(X = 3)$.',
        resposta: '$\\binom{10}{3}(0{,}3)^3(0{,}7)^7 \\approx 0{,}267$',
        passos: '$\\binom{10}{3} = 120$. $0{,}3^3 = 0{,}027$. $0{,}7^7 \\approx 0{,}08235$. Produto $\\approx 0{,}2668$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-75-binomial'],
      },
      {
        numero: 7,
        enunciado: 'IC 95% para média ($n = 100, \\bar x = 50, s = 10$).',
        resposta: '$[48{,}04,\\ 51{,}96]$',
        passos: 'Erro: $1{,}96 \\cdot s/\\sqrt n = 1{,}96 \\cdot 10/10 = 1{,}96$. IC: $50 \\pm 1{,}96$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-102-ic-media'],
      },
      {
        numero: 8,
        enunciado: 'Otimização: $f(x) = x e^{-x}$ em $[0, \\infty)$. Máximo?',
        resposta: '$x = 1$, $f(1) = 1/e$',
        passos: '$f\' = e^{-x} - x e^{-x} = e^{-x}(1 - x) = 0 \\Rightarrow x = 1$. $f\'\' < 0$ em $x = 1$, máximo.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-61-maximos-minimos'],
      },
      {
        numero: 9,
        enunciado: 'Black-Scholes (porta 15): $S = 100, K = 100, r = 0{,}05, \\sigma = 0{,}2, T = 1$. (Apenas plug — não calcule $N$.)',
        resposta: '$d_1 = (\\ln 1 + 0{,}07)/0{,}2 = 0{,}35$; $d_2 = 0{,}15$',
        passos: '$d_1 = [\\ln(S/K) + (r + \\sigma^2/2)T]/(\\sigma \\sqrt T) = (0 + 0{,}07)/0{,}2 = 0{,}35$. $d_2 = d_1 - \\sigma \\sqrt T = 0{,}15$.',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-119-bs-sintese'],
      },
      {
        numero: 10,
        enunciado: 'PCA: matriz de cov $\\begin{pmatrix} 4 & 1 \\\\ 1 & 3 \\end{pmatrix}$. Direção do PC1.',
        resposta: 'Autovetor associado a $\\lambda_1$ (maior)',
        passos: '$\\lambda^2 - 7\\lambda + 11 = 0$, $\\lambda = (7 \\pm \\sqrt{5})/2$. PC1 direção: autovetor de $\\lambda_1 = (7 + \\sqrt 5)/2$. Cálculo: $(A - \\lambda I)v = 0$.',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-118-pca'],
      },
      {
        numero: 11,
        enunciado: 'Demonstre Teorema Fundamental do Cálculo (esboço).',
        resposta: 'Definir $G(x) = \\int_a^x f$, mostrar $G\' = f$.',
        passos: 'Use definição de derivada: $G\'(x) = \\lim_{h \\to 0} (G(x+h) - G(x))/h = \\lim h^{-1} \\int_x^{x+h} f(t) dt$. Pela continuidade de $f$, esse limite é $f(x)$.',
        dificuldade: 'demonstracao',
        aulasCobertas: ['aula-83-tfc'],
      },
      {
        numero: 12,
        enunciado: 'Derive $f(x) = x^x$ (logaritmica).',
        resposta: '$f\'(x) = x^x (1 + \\ln x)$',
        passos: '$\\ln f = x \\ln x$. Derivando: $f\'/f = \\ln x + 1$. $f\' = x^x (\\ln x + 1)$.',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-53-regra-cadeia'],
      },
      {
        numero: 13,
        enunciado: 'Resolva $\\sin x + \\cos x = 1$ em $[0, 2\\pi)$.',
        resposta: '$x = 0$ ou $x = \\pi/2$',
        passos: '$\\sqrt 2 \\sin(x + \\pi/4) = 1 \\Rightarrow \\sin(x + \\pi/4) = 1/\\sqrt 2$. $x + \\pi/4 = \\pi/4$ ou $3\\pi/4 \\Rightarrow x = 0$ ou $\\pi/2$.',
        dificuldade: 'compreensao',
        aulasCobertas: ['aula-14-equacoes-trigonometricas'],
      },
      {
        numero: 14,
        enunciado: 'Em uma liga, defeito rate 2\\%. Em 100 itens, prob. de exato 3 defeitos.',
        resposta: '$\\binom{100}{3}(0{,}02)^3(0{,}98)^{97} \\approx 0{,}182$',
        passos: 'Binomial com $n=100, p=0{,}02$.',
        dificuldade: 'modelagem',
        aulasCobertas: ['aula-75-binomial'],
      },
      {
        numero: 15,
        enunciado: 'Black-Scholes mostra que toda matemática do EM converge. Liste 5 conceitos do programa que aparecem na fórmula $C = SN(d_1) - K e^{-rT} N(d_2)$.',
        resposta: 'Resposta esperada: 1) função (BS é função de S, K, r, T, σ); 2) logaritmo (em d₁); 3) exponencial (e^{-rT}); 4) integral (N como integral da normal); 5) derivada (Greeks).',
        passos: 'Veja porta formal de Black-Scholes em /financas-quantitativas/opcoes/black-scholes/. Cada conceito do programa aparece: log/exp das aulas 6-8; integral do Trim 9; derivadas dos Trims 6-7; PDE do Trim 10; distribuição normal do Trim 8.',
        dificuldade: 'desafio',
        aulasCobertas: ['aula-119-bs-sintese'],
      },
    ],
  },
]

export function getProvaById(id: string): Prova | undefined {
  return PROVAS.find((p) => p.id === id)
}
